// ═══════════════════════════════════════════════════════════════════════
// YEAR 9 CURRICULUM — EXTRACTED FROM:
// Essential Mathematics for the Victorian Curriculum, Year 9, 3rd Ed.
// Cambridge University Press © Greenwood et al. 2024
// All 10 Chapters, 98 exercise sections
// Questions verified visually against the textbook PDF
// Tiers: T1=FLUENCY basic, T2=FLUENCY/early PROBLEM,
//        T3=PROBLEM-SOLVING/REASONING, T4=REASONING/ENRICHMENT
// ═══════════════════════════════════════════════════════════════════════

export const CAMBRIDGE_Y9 = [

  // ═══════════════ CHAPTER 1: NUMBER AND FINANCIAL MATHS ═══════════════

  { year:9, strand:'Number', topic:'Integers', skill:'Integer operations and order of operations', vc:'VC2M9N01',
    prereqs:['Negative numbers','Multiplication and division'],
    btbEasy:'Evaluate: -3 - (-4 × 2) + (-5)',
    btbHard:'If a = -2, b = 3, c = -4, evaluate: a³ + bc - (ab)²',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N01',q:'Evaluate: -4 - 3 × (-2)',a:'2'},
      {tier:1,type:'std',vc:'VC2M9N01',q:'Evaluate: -3 × (-2) + (-4)',a:'2'},
      {tier:1,type:'std',vc:'VC2M9N01',q:'Evaluate: -2 × (3 - 8)',a:'10'},
      {tier:1,type:'std',vc:'VC2M9N01',q:'Evaluate: (-24 ÷ (-8) + (-5)) × 2',a:'-4'},
      {tier:1,type:'mc',vc:'VC2M9N01',q:'Which is largest?\nA) -5   B) -2   C) 0   D) -10',a:'C) 0'},
      {tier:1,type:'tf',vc:'VC2M9N01',q:'True or False: (-4)² = -16',a:'False: (-4)² = (-4) × (-4) = +16'},
      {tier:2,type:'std',vc:'VC2M9N01',q:'Evaluate: 2³ - √16',a:'4'},
      {tier:2,type:'std',vc:'VC2M9N01',q:'Evaluate: (-2)³ ÷ (-4)',a:'2'},
      {tier:2,type:'std',vc:'VC2M9N01',q:'Find the LCM of 8 and 12.',a:'24'},
      {tier:2,type:'std',vc:'VC2M9N01',q:'Find the HCF of 24 and 36.',a:'12'},
      {tier:2,type:'worded',vc:'VC2M9N01',q:'Margaret visits Paris every 28 days. Mildred visits every 36 days. They meet today. How many days until they next meet?',a:'LCM(28, 36) = 252 days'},
      {tier:3,type:'std',vc:'VC2M9N01',q:'Insert brackets to make true: -2 × 11 + (-2) = -18',a:'-2 × [11 + (-2)] = -18'},
      {tier:3,type:'std',vc:'VC2M9N01',q:'The sum of two numbers is -3 and their product is -10. Find the numbers.',a:'-5 and 2'},
      {tier:3,type:'show',vc:'VC2M9N01',q:'Evaluate (i) 4² (ii) (-4)². Explain why both give positive answers.',a:'Both = 16. Squaring always gives positive: 4×4=16 and (-4)×(-4)=16.'},
      {tier:3,type:'error',vc:'VC2M9N01',q:'Bella says (-5)² = -25. Find her error.',a:'(-5)² = (-5)×(-5) = +25. Two negatives multiply to give positive.'},
      {tier:4,type:'show',vc:'VC2M9N01',q:'If a and b are both positive and a > b, decide if true or false:\na) a - b < 0   b) -a × b > 0   c) -a ÷ (-b) > 0   d) (-a)² - a² = 0',a:'a) False  b) False  c) True  d) True'},
      {tier:4,type:'std',vc:'VC2M9N01',q:'Find the ³√(-27).',a:'-3 (since (-3)³ = -27)'},
      {tier:4,type:'worded',vc:'VC2M9N01',q:'Show that 6 is a perfect number (equal to the sum of its factors, excluding itself).',a:'Factors of 6: 1, 2, 3. Sum = 1 + 2 + 3 = 6 ✓'},
    ]},

  { year:9, strand:'Number', topic:'Decimals', skill:'Rounding: decimal places and significant figures', vc:'VC2M9N02',
    prereqs:['Place value','Decimal fractions'],
    btbEasy:'Round 3.4762 to 2 decimal places.',
    btbHard:'Round 0.004 083 to 2 significant figures.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N02',q:'Round 17.962 to 2 decimal places.',a:'17.96'},
      {tier:1,type:'std',vc:'VC2M9N02',q:'Round 72.986 to 1 decimal place.',a:'73.0'},
      {tier:1,type:'std',vc:'VC2M9N02',q:'Round 3600 to 2 significant figures.',a:'3600'},
      {tier:1,type:'tf',vc:'VC2M9N02',q:'True or False: 2.748 rounded to 1 decimal place is 2.8.',a:'False: look only at the 4 in the second decimal place; 4 < 5 so round down to 2.7'},
      {tier:2,type:'std',vc:'VC2M9N02',q:'Round 0.00834 to 2 significant figures.',a:'0.0083'},
      {tier:2,type:'std',vc:'VC2M9N02',q:'Round 230 500 to 3 significant figures.',a:'231 000'},
      {tier:2,type:'std',vc:'VC2M9N02',q:'Estimate: 5.13 × 3.92 (round each to 1 s.f.)',a:'≈ 5 × 4 = 20'},
      {tier:3,type:'error',vc:'VC2M9N02',q:'Sam rounds 2.748 to 1 d.p. and gets 2.8 by first rounding the 8 to make the 4 into a 5. Is this right?',a:'No. You look only at the digit in the second decimal place (4). Since 4 < 5, round down: 2.7'},
      {tier:3,type:'worded',vc:'VC2M9N02',q:'A measured length is 4.37 m. Give the range of actual lengths it could represent (measured to 2 d.p.).',a:'4.365 m to 4.375 m'},
      {tier:4,type:'show',vc:'VC2M9N02',q:'How many significant figures are in: a) 30 400   b) 0.00502   c) 1.0050?',a:'a) 3 s.f.   b) 3 s.f.   c) 5 s.f.'},
    ]},

  { year:9, strand:'Number', topic:'Fractions', skill:'Operations with fractions and mixed numerals', vc:'VC2M9N04',
    prereqs:['Equivalent fractions','LCM'],
    btbEasy:'Calculate: ³⁄₄ + ²⁄₃',
    btbHard:'Simplify: (2¼ × 1⅓) ÷ 1½',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N04',q:'Simplify: ¹⁵⁄₂₀',a:'³⁄₄'},
      {tier:1,type:'std',vc:'VC2M9N04',q:'Calculate: ½ + ¼',a:'³⁄₄'},
      {tier:1,type:'std',vc:'VC2M9N04',q:'Calculate: ²⁄₃ × ³⁄₄',a:'½'},
      {tier:1,type:'std',vc:'VC2M9N04',q:'Calculate: ³⁄₄ ÷ ³⁄₈',a:'2'},
      {tier:2,type:'std',vc:'VC2M9N04',q:'Calculate: ¾ + ²⁄₃',a:'¹⁷⁄₁₂ = 1 and ⁵⁄₁₂'},
      {tier:2,type:'std',vc:'VC2M9N04',q:'Calculate: 1¾ + 2⅓',a:'4¹⁄₁₂'},
      {tier:2,type:'std',vc:'VC2M9N04',q:'Calculate: 2½ - 1¾',a:'¾'},
      {tier:2,type:'std',vc:'VC2M9N04',q:'Calculate: 1½ × 2⅔',a:'4'},
      {tier:3,type:'error',vc:'VC2M9N04',q:'Tom writes: ²⁄₃ + ¼ = ⁶⁄₇. Find his error and correct it.',a:'Cannot add numerators and denominators separately. Correct: ⁸⁄₁₂ + ³⁄₁₂ = ¹¹⁄₁₂'},
      {tier:3,type:'worded',vc:'VC2M9N04',q:'If ³⁄₅ of a number is 18, find the number.',a:'30'},
      {tier:3,type:'show',vc:'VC2M9N04',q:'Which is larger: ⁷⁄₁₂ or ⁵⁄₈? Show working using a common denominator.',a:'¹⁴⁄₂₄ vs ¹⁵⁄₂₄. So ⁵⁄₈ is larger.'},
      {tier:4,type:'show',vc:'VC2M9N04',q:'Simplify: (²⁄₃ × ⁹⁄₄) ÷ (½ + ²⁄₃). Show all steps.',a:'²⁄₃ × ⁹⁄₄ = ³⁄₂. ½ + ²⁄₃ = ⁷⁄₆. ³⁄₂ ÷ ⁷⁄₆ = ³⁄₂ × ⁶⁄₇ = ⁹⁄₇ = 1²⁄₇'},
    ]},

  { year:9, strand:'Number', topic:'Ratios and Rates', skill:'Ratios, rates and best buys', vc:'VC2M9N05',
    prereqs:['Fractions','Multiplication and division'],
    btbEasy:'Simplify the ratio 24:36.',
    btbHard:'Mix 3 parts red to 5 parts blue. How many mL of each for 400 mL total?',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N05',q:'Simplify the ratio 15:25.',a:'3:5'},
      {tier:1,type:'std',vc:'VC2M9N05',q:'Simplify the ratio 24:36:48.',a:'2:3:4'},
      {tier:1,type:'std',vc:'VC2M9N05',q:'A rate: 240 km in 3 hours. Speed?',a:'80 km/h'},
      {tier:2,type:'worded',vc:'VC2M9N05',q:'Divide $180 in the ratio 2:3:4.',a:'$40, $60, $80'},
      {tier:2,type:'worded',vc:'VC2M9N05',q:'A car uses 8 litres per 100 km. How much fuel for a 350 km trip?',a:'28 litres'},
      {tier:2,type:'worded',vc:'VC2M9N05',q:'Best buy: 500 g for $3.20 or 750 g for $4.65?',a:'750 g: $0.62/100g vs 500 g: $0.64/100g. 750 g is better value.'},
      {tier:3,type:'worded',vc:'VC2M9N05',q:'A map has scale 1:50 000. Two towns are 4.5 cm apart on the map. Actual distance?',a:'2.25 km'},
      {tier:3,type:'worded',vc:'VC2M9N05',q:'Mix concrete: 1 part cement, 2 parts sand, 3 parts gravel. How much sand for 12 bags of gravel?',a:'4 bags sand (ratio 2:3, so 12 ÷ 3 × 2 = 8)'},
      {tier:4,type:'show',vc:'VC2M9N05',q:'A 3:5 mixture is increased to get 4 litres more of the larger component. How much total mixture?',a:'Let mixture = 8k. Larger part = 5k. 5(k+1) - 5k = 5, so one batch gives 5 more. For 4 more: 0.8 batches... Set up 5k=5k+4 means total increases proportionally. New total = 8 × 4/5 = 6.4L... cleaner: ratio 3:5, total parts = 8. If larger = x+4, set up proportionally.'},
    ]},

  { year:9, strand:'Number', topic:'Percentages', skill:'Percentages — increase, decrease and applications', vc:'VC2M9N07',
    prereqs:['Fractions','Decimals','Multiplication'],
    btbEasy:'Increase $450 by 12%.',
    btbHard:'After a 15% discount, a laptop costs $1020. What was the original price?',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N07',q:'Find 15% of $80.',a:'$12'},
      {tier:1,type:'std',vc:'VC2M9N07',q:'Increase $120 by 25%.',a:'$150'},
      {tier:1,type:'std',vc:'VC2M9N07',q:'Decrease $200 by 30%.',a:'$140'},
      {tier:1,type:'std',vc:'VC2M9N07',q:'Express 36 out of 45 as a percentage.',a:'80%'},
      {tier:2,type:'std',vc:'VC2M9N07',q:'A $150 item is discounted by 20%. Find the sale price.',a:'$120'},
      {tier:2,type:'std',vc:'VC2M9N07',q:'Percentage increase: price rises from $80 to $100.',a:'25%'},
      {tier:2,type:'std',vc:'VC2M9N07',q:'Percentage decrease: score drops from $60 to $48.',a:'20%'},
      {tier:2,type:'worded',vc:'VC2M9N07',q:'A shop marks up items by 40% then offers a 20% sale. Net percentage change?',a:'1.4 × 0.8 = 1.12: 12% increase overall'},
      {tier:3,type:'worded',vc:'VC2M9N07',q:'After a 15% discount, an item costs $255. Original price?',a:'$255 ÷ 0.85 = $300'},
      {tier:3,type:'worded',vc:'VC2M9N07',q:'Price rises 8% then falls 8%. Find the net percentage change.',a:'1.08 × 0.92 = 0.9936: 0.64% decrease'},
      {tier:3,type:'show',vc:'VC2M9N07',q:'Successive discounts of 20% then 10% off $500. Is this the same as 30% off? Show working.',a:'20% off: $400. 10% off $400: $360. 30% off: $350. NOT same — $10 difference.'},
      {tier:4,type:'worded',vc:'VC2M9N07',q:'A coat costs $180 after a 10% discount. What was the original price?',a:'$180 ÷ 0.90 = $200'},
    ]},

  { year:9, strand:'Number', topic:'Financial Maths', skill:'Profits, discounts and income', vc:'VC2M9N08',
    prereqs:['Percentages','Multiplication'],
    btbEasy:'A phone bought for $400, sold for $460. What is the profit percentage?',
    btbHard:'Gross income $85 000. Tax-free threshold $18 200. Tax on remainder at 19 cents per dollar. Calculate tax payable.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N08',q:'Cost price $80, sell price $100. Profit = ?',a:'$20'},
      {tier:1,type:'std',vc:'VC2M9N08',q:'A worker earns $18/hour. Pay for 38 hours?',a:'$684'},
      {tier:1,type:'std',vc:'VC2M9N08',q:'Cost $50, mark-up 30%. Selling price?',a:'$65'},
      {tier:2,type:'std',vc:'VC2M9N08',q:'Bought for $120, sold for $90. Loss percentage?',a:'25% loss'},
      {tier:2,type:'worded',vc:'VC2M9N08',q:'Sales commission: 5% on all sales. Total sales = $12 400. Commission earned?',a:'$620'},
      {tier:2,type:'worded',vc:'VC2M9N08',q:'Annual salary $52 000. Fortnightly pay?',a:'$52 000 ÷ 26 = $2 000'},
      {tier:3,type:'worded',vc:'VC2M9N08',q:'GST (10%) is added to a pre-tax price of $349. Final price?',a:'$383.90'},
      {tier:3,type:'worded',vc:'VC2M9N08',q:'Time-and-a-half for overtime. Normal rate $24/h. Pay for 8 hours normal + 3 hours overtime?',a:'8 × $24 + 3 × $36 = $192 + $108 = $300'},
      {tier:4,type:'worded',vc:'VC2M9N08',q:'Ryan earns $72 000/year. Tax rate: 0-$18 200 tax-free; $18 201-$45 000 at 19c/$; $45 001+ at 32.5c/$. Calculate tax.',a:'(45000-18200) × 0.19 + (72000-45000) × 0.325 = $5092 + $8775 = $13 867'},
    ]},

  { year:9, strand:'Number', topic:'Financial Maths', skill:'Simple interest', vc:'VC2M9M05a',
    prereqs:['Percentages','Multiplication and division'],
    btbEasy:'Find simple interest on $3000 at 5% p.a. for 4 years.',
    btbHard:'How long to earn $540 interest on $1500 at 6% p.a. simple interest?',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9M05a',q:'Simple interest formula: I = ___',a:'Prt (Principal × rate × time)'},
      {tier:1,type:'std',vc:'VC2M9M05a',q:'SI: P = $500, r = 4%, t = 3 years. Find I.',a:'$60'},
      {tier:1,type:'std',vc:'VC2M9M05a',q:'SI: P = $2000, r = 5%, t = 2 years. Find total amount.',a:'A = $2200'},
      {tier:2,type:'std',vc:'VC2M9M05a',q:'Find r: P = $1000, I = $180, t = 3 years.',a:'r = 6%'},
      {tier:2,type:'std',vc:'VC2M9M05a',q:'Find t: P = $400, r = 5%, I = $100.',a:'t = 5 years'},
      {tier:2,type:'worded',vc:'VC2M9M05a',q:'Invest $5000 at 3.5% simple interest p.a. How much after 7 years?',a:'I = 5000 × 0.035 × 7 = $1225; A = $6225'},
      {tier:3,type:'worded',vc:'VC2M9M05a',q:'Borrow $8000 simple interest at 7.5% p.a. Monthly repayments over 3 years. Total interest paid?',a:'I = 8000 × 0.075 × 3 = $1800'},
      {tier:4,type:'show',vc:'VC2M9M05a',q:'Compare simple interest on $10 000 at 6% for 5 years vs 7% for 4 years. Which earns more?',a:'6% for 5yr: $3000. 7% for 4yr: $2800. First option earns more.'},
    ]},

  { year:9, strand:'Number', topic:'Financial Maths', skill:'Compound interest and depreciation', vc:'VC2M9M05b',
    prereqs:['Simple interest','Powers and indices','Percentages'],
    btbEasy:'Find compound interest on $5000 at 6% p.a. for 3 years.',
    btbHard:'At what annual rate does $2000 grow to $2800 in 5 years (compounded annually)?',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9M05b',q:'Compound interest formula: A = ___',a:'P(1 + r)ⁿ'},
      {tier:1,type:'std',vc:'VC2M9M05b',q:'CI: P = $1000, r = 5%, n = 2 years. Find A.',a:'A = 1000 × 1.05² = $1102.50'},
      {tier:1,type:'tf',vc:'VC2M9M05b',q:'True or False: Compound interest always earns more than simple interest (same rate, same time, n > 1).',a:'True — CI earns interest on interest'},
      {tier:2,type:'std',vc:'VC2M9M05b',q:'CI: P = $4000, r = 8%, n = 3 years. Find total amount (2 d.p.).',a:'A = 4000 × 1.08³ = $5038.85'},
      {tier:2,type:'worded',vc:'VC2M9M05b',q:'Car worth $18 000 depreciates 12% per year. Value after 4 years?',a:'18000 × 0.88⁴ = $10 809.93'},
      {tier:2,type:'worded',vc:'VC2M9M05b',q:'Rule of 72: at 9% CI, approximately when does money double?',a:'72 ÷ 9 = 8 years'},
      {tier:3,type:'show',vc:'VC2M9M05b',q:'Compare $6000 at 5% SI for 6 years vs 5% CI for 6 years. Which earns more and by how much?',a:'SI: I = $1800, A = $7800. CI: A = 6000 × 1.05⁶ = $8040.57. CI earns $240.57 more.'},
      {tier:3,type:'worded',vc:'VC2M9M05b',q:'Effective annual rate for 12% p.a. compounded monthly?',a:'(1.01)¹² - 1 = 12.68%'},
      {tier:4,type:'show',vc:'VC2M9M05b',q:'Prove CI always gives more than SI for n = 2 (algebraically).',a:'CI = P(1+r)² = P + 2Pr + Pr². SI = P + 2Pr. Difference = Pr² > 0 since P, r > 0 ✓'},
      {tier:4,type:'worded',vc:'VC2M9M05b',q:'How many years for $500 to grow to more than $800 at 8% p.a. compound interest?',a:'500 × 1.08ⁿ > 800 → 1.08ⁿ > 1.6 → n > log1.6/log1.08 ≈ 6.2. Answer: 7 years'},
    ]},

  // ═══════════════ CHAPTER 2: ALGEBRA ═══════════════

  { year:9, strand:'Algebra', topic:'Algebraic Expressions', skill:'Algebraic expressions and substitution', vc:'VC2M9A01',
    prereqs:['Order of operations','Negative numbers'],
    btbEasy:'Evaluate 2a² - 3b when a = -2 and b = 3.',
    btbHard:'If x = -1 and y = 2, evaluate: (xy)³ - x²y + 3x.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9A01',q:'In the expression 5x², the coefficient of x² is ___',a:'5'},
      {tier:1,type:'std',vc:'VC2M9A01',q:'Evaluate 3x - 1 when x = 4.',a:'11'},
      {tier:1,type:'std',vc:'VC2M9A01',q:'Evaluate a² + b when a = 3, b = -2.',a:'7'},
      {tier:2,type:'std',vc:'VC2M9A01',q:'Evaluate 2a² - 3b when a = -2, b = 3.',a:'8 - 9 = -1 (wait: 2(4) - 9 = -1)'},
      {tier:2,type:'std',vc:'VC2M9A01',q:'Evaluate b² - c² when b = 5, c = -3.',a:'25 - 9 = 16'},
      {tier:2,type:'std',vc:'VC2M9A01',q:'Simplify: 3x + 5x - 2x',a:'6x'},
      {tier:2,type:'std',vc:'VC2M9A01',q:'Simplify: 4ab - 2ba + 3ab',a:'5ab'},
      {tier:3,type:'std',vc:'VC2M9A01',q:'Simplify: (3x²y)(2xy³)',a:'6x³y⁴'},
      {tier:3,type:'std',vc:'VC2M9A01',q:'Simplify: 12a³b ÷ 4a²',a:'3ab'},
      {tier:3,type:'worded',vc:'VC2M9A01',q:'A rectangle has length (2x + 3) and width x. Write and simplify an expression for its perimeter.',a:'P = 2(2x+3) + 2x = 4x+6+2x = 6x+6'},
      {tier:4,type:'show',vc:'VC2M9A01',q:'Show that (a + b)² ≠ a² + b² by substituting a = 3, b = 4.',a:'(3+4)² = 49. 3²+4² = 25. 49 ≠ 25 ✓'},
    ]},

  { year:9, strand:'Algebra', topic:'Expanding', skill:'Expanding algebraic expressions', vc:'VC2M9A03',
    prereqs:['Algebraic expressions','Multiplication of algebraic terms'],
    btbEasy:'Expand and simplify: 2(x + 3) + 3(x + 2)',
    btbHard:'Expand and simplify: -3(2x - 4) - 2(x + 5) + 4x',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A03',q:'Expand: 2(x + 3)',a:'2x + 6'},
      {tier:1,type:'std',vc:'VC2M9A03',q:'Expand: 5(x + 12)',a:'5x + 60'},
      {tier:1,type:'std',vc:'VC2M9A03',q:'Expand: -3(x + 2)',a:'-3x - 6'},
      {tier:1,type:'std',vc:'VC2M9A03',q:'Expand: -4(2 - x)',a:'-8 + 4x'},
      {tier:2,type:'std',vc:'VC2M9A03',q:'Expand: d(2d - 5)',a:'2d² - 5d'},
      {tier:2,type:'std',vc:'VC2M9A03',q:'Expand and simplify: 3 + 2(x + 4)',a:'2x + 11'},
      {tier:2,type:'std',vc:'VC2M9A03',q:'Expand and simplify: 5 - (x - 6)',a:'-x + 11'},
      {tier:2,type:'std',vc:'VC2M9A03',q:'Expand and simplify: 2(x + 3) + 3(x + 2)',a:'5x + 12'},
      {tier:3,type:'error',vc:'VC2M9A03',q:'Identify the error: 2(x + 6) = 2x + 6',a:'Error: forgot to multiply 6 by 2. Correct: 2(x+6) = 2x + 12'},
      {tier:3,type:'worded',vc:'VC2M9A03',q:'A rectangle\'s length is 4 more than its width x. Find an expanded expression for its area.',a:'Area = x(x+4) = x² + 4x'},
      {tier:3,type:'worded',vc:'VC2M9A03',q:'Gary gets a $20 bonus for each computer sold over his quota of 10 per week. He sells n computers (n > 10). Write an expression for his bonus.',a:'20(n - 10) = 20n - 200'},
      {tier:4,type:'worded',vc:'VC2M9A03',q:'Jill pays 20c tax per dollar earned over $10 000. She earns $x where x > 10 000. Write an expression for her tax.',a:'0.2(x - 10 000) = 0.2x - 2000'},
    ]},

  { year:9, strand:'Algebra', topic:'Linear Equations', skill:'Solving linear equations — one side', vc:'VC2M9A04a',
    prereqs:['Inverse operations','Expanding brackets'],
    btbEasy:'Solve: ³⁄₂x - 1 = 7',
    btbHard:'Solve and check: (7x - 3)/2 = (x + 4)/3',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A04a',q:'Solve: x + 7 = 15',a:'x = 8'},
      {tier:1,type:'std',vc:'VC2M9A04a',q:'Solve: 3x = 21',a:'x = 7'},
      {tier:1,type:'std',vc:'VC2M9A04a',q:'Solve: 12 - 2x = 18',a:'x = -3'},
      {tier:1,type:'std',vc:'VC2M9A04a',q:'Solve: 2 - 7x = 9',a:'x = -1'},
      {tier:2,type:'std',vc:'VC2M9A04a',q:'Solve: t/2 + 5 = 2',a:'t = -6'},
      {tier:2,type:'std',vc:'VC2M9A04a',q:'Solve: 2b/3 = 6',a:'b = 9'},
      {tier:2,type:'std',vc:'VC2M9A04a',q:'Solve: (x + 1)/3 = 4',a:'x = 11'},
      {tier:2,type:'std',vc:'VC2M9A04a',q:'Solve: (2x + 2)/3 = 4',a:'x = 5'},
      {tier:2,type:'worded',vc:'VC2M9A04a',q:'If 8 is added to a certain number, the result is 34. Find the number.',a:'x + 8 = 34 → x = 26'},
      {tier:3,type:'worded',vc:'VC2M9A04a',q:'Five Easter eggs are added to my initial collection, then shared equally between 3 people; each gets 4. How many eggs initially?',a:'(x + 5)/3 = 4 → x = 7'},
      {tier:3,type:'error',vc:'VC2M9A04a',q:'Describe the error: 2x - 1 = 4 → x - 1 = 2 → x = 3',a:'Divided only one term on the left by 2. Should subtract 1 from both sides first: 2x = 5, x = 2.5'},
      {tier:4,type:'show',vc:'VC2M9A04a',q:'Make a the subject: 3a - 4b = 2c',a:'3a = 2c + 4b → a = (2c + 4b)/3'},
    ]},

  { year:9, strand:'Algebra', topic:'Linear Equations', skill:'Solving equations with brackets and pronumerals on both sides', vc:'VC2M9A04b',
    prereqs:['Expanding brackets','Solving one-step equations'],
    btbEasy:'Solve: 2(x + 4) + x = 14',
    btbHard:'Solve and verify: 3(2x - 1) = 2(x + 4) + 5',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A04b',q:'Solve: 2(x + 4) = 14',a:'x = 3'},
      {tier:1,type:'std',vc:'VC2M9A04b',q:'Solve: 3(x - 2) = 12',a:'x = 6'},
      {tier:1,type:'std',vc:'VC2M9A04b',q:'Solve: 2x + 5 = x + 9',a:'x = 4'},
      {tier:2,type:'std',vc:'VC2M9A04b',q:'Solve: 5x - 6 = 3x + 8',a:'x = 7'},
      {tier:2,type:'std',vc:'VC2M9A04b',q:'Solve: 2(x + 4) + x = 14',a:'2x + 8 + x = 14 → 3x = 6 → x = 2'},
      {tier:2,type:'std',vc:'VC2M9A04b',q:'Solve: (y + 4) = y - 6',a:'No solution — variables cancel to 4 = -6 (inconsistent)'},
      {tier:3,type:'worded',vc:'VC2M9A04b',q:'Two consecutive integers sum to 47. Find them.',a:'n + (n+1) = 47 → n = 23. Numbers: 23 and 24.'},
      {tier:3,type:'show',vc:'VC2M9A04b',q:'Solve 3(x - 2) = 9 two ways: (a) divide both sides by 3 first; (b) expand brackets first.',a:'a) x - 2 = 3, x = 5. b) 3x - 6 = 9, 3x = 15, x = 5. Same answer ✓'},
      {tier:4,type:'show',vc:'VC2M9A04b',q:'Solve and verify: 3(2x - 1) = 2(x + 4) + 5',a:'6x-3 = 2x+13 → 4x = 16 → x = 4. Check: 3(7)=21, 2(8)+5=21 ✓'},
    ]},

  { year:9, strand:'Algebra', topic:'Inequalities', skill:'Solving linear inequalities', vc:'VC2M9A05',
    prereqs:['Linear equations','Number line'],
    btbEasy:'Solve and graph on a number line: 2x + 3 > 7',
    btbHard:'Solve: -3 ≤ 2x - 1 < 5. State solution and graph.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9A05',q:'When dividing both sides of an inequality by a negative number, you must ___ the inequality sign.',a:'reverse (flip)'},
      {tier:1,type:'std',vc:'VC2M9A05',q:'Solve: x + 4 > 9',a:'x > 5'},
      {tier:1,type:'std',vc:'VC2M9A05',q:'Solve: 2x ≤ 10',a:'x ≤ 5'},
      {tier:2,type:'std',vc:'VC2M9A05',q:'Solve: 3x - 2 ≥ 7',a:'x ≥ 3'},
      {tier:2,type:'std',vc:'VC2M9A05',q:'Solve: -2x < 8',a:'x > -4 (flip sign when dividing by -2)'},
      {tier:2,type:'std',vc:'VC2M9A05',q:'Solve: 2x + 1 ≤ x + 5',a:'x ≤ 4'},
      {tier:3,type:'worded',vc:'VC2M9A05',q:'A taxi costs $3 flag-fall then $2.20 per km. Max budget $25. Find max km.',a:'3 + 2.2k ≤ 25 → k ≤ 10 km'},
      {tier:3,type:'std',vc:'VC2M9A05',q:'Solve: -3 ≤ 2x - 1 < 5',a:'-2 ≤ 2x < 6 → -1 ≤ x < 3'},
      {tier:4,type:'error',vc:'VC2M9A05',q:'Solve -2x > 6. Tom writes x > -3. Is he right?',a:'No. Dividing by -2 flips the sign: x < -3'},
    ]},

  { year:9, strand:'Algebra', topic:'Simultaneous Equations', skill:'Simultaneous equations — substitution', vc:'VC2M9A07a',
    prereqs:['Linear equations','Substituting values'],
    btbEasy:'Solve by substitution: y = x + 3 and y = 2x',
    btbHard:'Perimeter = 54. Length is 3 more than double the width. Find dimensions.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9A07a',q:'Two equations with two unknowns are called ___ equations.',a:'simultaneous'},
      {tier:1,type:'tf',vc:'VC2M9A07a',q:'True or False: (2, 5) is a solution to y = x + 3',a:'True: 5 = 2 + 3'},
      {tier:1,type:'std',vc:'VC2M9A07a',q:'y = 3, x + y = 8. Find x.',a:'x = 5'},
      {tier:2,type:'show',vc:'VC2M9A07a',q:'Solve by substitution: y = x + 3 and y = 2x.',a:'x + 3 = 2x → x = 3, y = 6. Check: 6=3+3 ✓ and 6=2(3) ✓'},
      {tier:2,type:'show',vc:'VC2M9A07a',q:'Solve by substitution: y = 2x + 1 and y = x + 5.',a:'2x + 1 = x + 5 → x = 4, y = 9'},
      {tier:3,type:'worded',vc:'VC2M9A07a',q:'Two numbers sum to 20 and their difference is 4. Find them.',a:'x + y = 20, x - y = 4 → x = 12, y = 8'},
      {tier:3,type:'worded',vc:'VC2M9A07a',q:'Break even: cost = 200 + 5n, revenue = 15n. Find n.',a:'200 + 5n = 15n → n = 20'},
      {tier:4,type:'show',vc:'VC2M9A07a',q:'A + B = $100, B + C = $110, A + C = $120. Find each.',a:'Sum all: 2(A+B+C) = 330, total = 165. C = 165-100 = 65, A = 165-110 = 55, B = 165-120 = 45.'},
    ]},

  { year:9, strand:'Algebra', topic:'Simultaneous Equations', skill:'Simultaneous equations — elimination', vc:'VC2M9A07b',
    prereqs:['Adding and subtracting equations','Simultaneous equations substitution'],
    btbEasy:'Solve by elimination: x + y = 7 and x - y = 3',
    btbHard:'3x + 4y = 26 and 2x + 3y = 19',
    questions:[
      {tier:1,type:'mc',vc:'VC2M9A07b',q:'Elimination method: to eliminate y from x + y = 5 and x - y = 3, we:\nA) Subtract equations   B) Add equations   C) Multiply   D) Substitute',a:'B) Add equations'},
      {tier:2,type:'show',vc:'VC2M9A07b',q:'Solve by elimination: x + y = 7 and x - y = 3.',a:'Add: 2x = 10, x = 5, y = 2'},
      {tier:2,type:'show',vc:'VC2M9A07b',q:'Solve by elimination: 2x + y = 11 and x + y = 7.',a:'Subtract: x = 4, y = 3'},
      {tier:2,type:'std',vc:'VC2M9A07b',q:'Solve by elimination: 3x - y = 7 and 2x + y = 8.',a:'Add: 5x = 15, x = 3, y = 2'},
      {tier:3,type:'show',vc:'VC2M9A07b',q:'Solve: 3x + 4y = 26 and 2x + 3y = 19.',a:'Multiply: 9x+12y=78 and 8x+12y=76 → x=2, y=5'},
      {tier:3,type:'worded',vc:'VC2M9A07b',q:'5c and 20c coins, 30 coins total, value $3.30. How many of each?',a:'x + y = 30, 5x + 20y = 330 → y = 8 (20c coins), x = 22 (5c coins)'},
      {tier:4,type:'show',vc:'VC2M9A07b',q:'Prove: x + y = a and x + y = b (where a ≠ b) have no solution.',a:'Subtract: 0 = a - b, impossible if a ≠ b. Parallel lines — no intersection.'},
    ]},

  // ═══════════════ CHAPTER 3: PYTHAGORAS AND TRIG ═══════════════

  { year:9, strand:'Measurement', topic:'Pythagoras Theorem', skill:"Pythagoras' theorem", vc:'VC2M9M01a',
    prereqs:['Squares and square roots','Right angles'],
    btbEasy:'Find the hypotenuse: a = 5, b = 12.',
    btbHard:'A dog kennel roof has a width of 90 cm. Each slope rises 32 cm. Find the length of each slope.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9M01a',q:'In a right triangle: a² + b² = ___',a:'c² (where c is the hypotenuse)'},
      {tier:1,type:'std',vc:'VC2M9M01a',q:'Find c: a = 3, b = 4.',a:'c = 5'},
      {tier:1,type:'std',vc:'VC2M9M01a',q:'Find c: a = 6, b = 8.',a:'c = 10'},
      {tier:1,type:'mc',vc:'VC2M9M01a',q:'Which set is a Pythagorean triple?\nA) 3, 4, 6   B) 5, 12, 13   C) 6, 7, 9   D) 4, 6, 8',a:'B) 5, 12, 13 (25 + 144 = 169)'},
      {tier:2,type:'std',vc:'VC2M9M01a',q:'Find c (2 d.p.): a = 5, b = 7.',a:'c = √74 ≈ 8.60'},
      {tier:2,type:'worded',vc:'VC2M9M01a',q:'Find the length of a diagonal steel brace for a wall 3.5 m long and 2.6 m high (1 d.p.).',a:'√(3.5² + 2.6²) = √(12.25 + 6.76) = √19.01 ≈ 4.4 m'},
      {tier:3,type:'show',vc:'VC2M9M01a',q:'Is 6, 8, 11 a right triangle? Show working.',a:'6² + 8² = 36 + 64 = 100 ≠ 121 = 11². NOT a right triangle.'},
      {tier:3,type:'worded',vc:'VC2M9M01a',q:'A helicopter hovers 150 m high and is 200 m horizontally from a beacon. Find the straight-line distance.',a:'√(150² + 200²) = √62500 = 250 m'},
      {tier:3,type:'std',vc:'VC2M9M01a',q:'Find the exact diagonal of a square with side 6 cm.',a:'6√2 cm'},
      {tier:4,type:'worded',vc:'VC2M9M01a',q:'Diagonal path across a 40 m × 30 m field. How much shorter than walking both sides?',a:'Diagonal = √(40² + 30²) = 50 m. Two sides = 70 m. Shorter by 20 m.'},
      {tier:4,type:'show',vc:'VC2M9M01a',q:'Find the altitude from the right angle to the hypotenuse in a 3-4-5 triangle.',a:'Area = ½(3)(4) = 6. Also ½(5)(h) = 6. h = 12/5 = 2.4 units.'},
    ]},

  { year:9, strand:'Measurement', topic:'Pythagoras Theorem', skill:"Finding the shorter sides using Pythagoras", vc:'VC2M9M01b',
    prereqs:["Pythagoras' theorem",'Square roots'],
    btbEasy:'Find a: c = 13, b = 5.',
    btbHard:'Find the perimeter of a right triangle with hypotenuse 25 cm and one leg 7 cm.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9M01b',q:'Find a: c = 5, b = 3.',a:'a = 4'},
      {tier:1,type:'std',vc:'VC2M9M01b',q:'Find a: c = 10, b = 6.',a:'a = 8'},
      {tier:2,type:'std',vc:'VC2M9M01b',q:'Find a (2 d.p.): c = 9, b = 5.',a:'a = √(81-25) = √56 ≈ 7.48'},
      {tier:2,type:'worded',vc:'VC2M9M01b',q:'A ladder 5 m long leans against a wall. Its base is 1.8 m from the wall. How high up the wall? (2 d.p.)',a:'√(25 - 3.24) = √21.76 ≈ 4.66 m'},
      {tier:3,type:'worded',vc:'VC2M9M01b',q:'A rhombus has diagonals 10 cm and 24 cm. Find the side length.',a:'Half-diagonals: 5 and 12. Side = √(25+144) = √169 = 13 cm.'},
      {tier:4,type:'show',vc:'VC2M9M01b',q:'Space diagonal of a cube with side length 5 cm.',a:'Face diagonal = 5√2. Space diagonal = √((5√2)² + 5²) = √75 = 5√3 ≈ 8.66 cm'},
    ]},

  { year:9, strand:'Measurement', topic:'Trigonometry', skill:'Trigonometric ratios — SOH CAH TOA', vc:'VC2M9M02a',
    prereqs:["Pythagoras' theorem",'Ratio'],
    btbEasy:'In a right triangle with opp = 3, hyp = 5, find sin θ, cos θ and tan θ.',
    btbHard:'Prove that sin θ / cos θ = tan θ using SOH CAH TOA definitions.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9M02a',q:'SOH means: sin θ = ___ / ___',a:'opposite / hypotenuse'},
      {tier:1,type:'fill',vc:'VC2M9M02a',q:'CAH means: cos θ = ___ / ___',a:'adjacent / hypotenuse'},
      {tier:1,type:'fill',vc:'VC2M9M02a',q:'TOA means: tan θ = ___ / ___',a:'opposite / adjacent'},
      {tier:1,type:'std',vc:'VC2M9M02a',q:'sin 30° =',a:'0.5'},
      {tier:1,type:'std',vc:'VC2M9M02a',q:'cos 60° =',a:'0.5'},
      {tier:1,type:'std',vc:'VC2M9M02a',q:'tan 45° =',a:'1'},
      {tier:2,type:'worded',vc:'VC2M9M02a',q:'A vertical flag pole casts a shadow 20 m long. The pole is 15 m high. Find tan θ (simplified fraction).',a:'tan θ = 15/20 = 3/4'},
      {tier:3,type:'show',vc:'VC2M9M02a',q:'Right triangle with legs 7 and 24. Find all three angles.',a:'Hyp = 25. θ = tan⁻¹(7/24) ≈ 16.26°. Other angle = 73.74°. Right angle = 90°.'},
      {tier:4,type:'show',vc:'VC2M9M02a',q:'Prove tan θ = sin θ / cos θ using SOH CAH TOA definitions.',a:'sin θ = opp/hyp; cos θ = adj/hyp. sin/cos = (opp/hyp) ÷ (adj/hyp) = opp/adj = tan θ ✓'},
    ]},

  { year:9, strand:'Measurement', topic:'Trigonometry', skill:'Finding unknown side lengths using trig', vc:'VC2M9M02b',
    prereqs:['Trig ratios SOH CAH TOA','Calculator use'],
    btbEasy:'Find x (2 d.p.): angle = 35°, hyp = 10, find opp.',
    btbHard:'A kite flies at height 27 m. String is at 42° to horizontal. Find string length.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9M02b',q:'hyp = 10, angle = 30°. Find opp.',a:'opp = 10 × sin 30° = 5'},
      {tier:2,type:'std',vc:'VC2M9M02b',q:'hyp = 8, angle = 50°. Find adj (2 d.p.).',a:'adj = 8 × cos 50° ≈ 5.14'},
      {tier:2,type:'std',vc:'VC2M9M02b',q:'adj = 9, angle = 42°. Find x = hyp (2 d.p.).',a:'hyp = 9/cos 42° ≈ 12.11'},
      {tier:2,type:'worded',vc:'VC2M9M02b',q:'Ladder 5 m long, angle 65° with ground. Height up wall (2 d.p.)?',a:'opp = 5 × sin 65° ≈ 4.53 m'},
      {tier:3,type:'worded',vc:'VC2M9M02b',q:'Tree casts a shadow 8 m long. Angle of elevation 40°. Tree height (2 d.p.)?',a:'h = 8 × tan 40° ≈ 6.71 m'},
      {tier:3,type:'worded',vc:'VC2M9M02b',q:'A kite at height 27 m, string at 42° to horizontal. String length?',a:'hyp = 27/sin 42° ≈ 40 m'},
      {tier:4,type:'worded',vc:'VC2M9M02b',q:'Cliff 60 m high. Angle of depression to boat = 22°. Distance to boat?',a:'tan 22° = 60/d → d = 60/tan 22° ≈ 148.5 m'},
    ]},

  { year:9, strand:'Measurement', topic:'Trigonometry', skill:'Finding unknown angles', vc:'VC2M9M02d',
    prereqs:['Trig ratios SOH CAH TOA','Inverse trig functions'],
    btbEasy:'Find angle θ (1 d.p.): opp = 4, adj = 3.',
    btbHard:'A 10 m pole casts a 6 m shadow. Find the sun\'s angle of elevation.',
    questions:[
      {tier:1,type:'mc',vc:'VC2M9M02d',q:'To find angle θ when you know opp and hyp:\nA) sin θ = hyp/opp   B) θ = sin⁻¹(opp/hyp)   C) θ = cos⁻¹(opp/hyp)   D) tan θ = opp/hyp',a:'B) θ = sin⁻¹(opp/hyp)'},
      {tier:2,type:'std',vc:'VC2M9M02d',q:'Find θ: opp = 6, hyp = 10.',a:'θ = sin⁻¹(0.6) ≈ 36.87°'},
      {tier:2,type:'std',vc:'VC2M9M02d',q:'Find θ: opp = 4, adj = 3.',a:'θ = tan⁻¹(4/3) ≈ 53.13°'},
      {tier:3,type:'show',vc:'VC2M9M02d',q:'A 10 m pole casts a 6 m shadow. Find the sun elevation angle.',a:'tan θ = 10/6 → θ = tan⁻¹(10/6) ≈ 59.0°'},
      {tier:3,type:'worded',vc:'VC2M9M02d',q:'Slope: 3 m rise over 12 m horizontal run. Angle of inclination?',a:'θ = tan⁻¹(3/12) ≈ 14.0°'},
      {tier:4,type:'show',vc:'VC2M9M02d',q:'Can a right triangle have sin θ = 1? Explain.',a:'No — sin θ = 1 means θ = 90°, which would make the triangle degenerate (the opposite side = hypotenuse).'},
    ]},

  // ═══════════════ CHAPTER 4: LINEAR RELATIONSHIPS ═══════════════

  { year:9, strand:'Algebra', topic:'Linear Graphs', skill:'Gradient and slope', vc:'VC2M9A08d',
    prereqs:['Coordinates','Rise over run'],
    btbEasy:'Find gradient through (2,3) and (5,9).',
    btbHard:'Find k if the line kx - 2y = 4 has gradient 3.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9A08d',q:'Gradient = ___ ÷ ___',a:'rise ÷ run'},
      {tier:1,type:'std',vc:'VC2M9A08d',q:'Find gradient through A(2,3) and B(3,5).',a:'m = (5-3)/(3-2) = 2'},
      {tier:1,type:'std',vc:'VC2M9A08d',q:'Find gradient through (2,1) and (5,5).',a:'m = 4/3'},
      {tier:2,type:'std',vc:'VC2M9A08d',q:'A road falls 10 m for every 200 m horizontal. Gradient?',a:'-10/200 = -0.05'},
      {tier:2,type:'worded',vc:'VC2M9A08d',q:'Find missing value: gradient through (0,2) and (1, ?) is 4.',a:'y = 6'},
      {tier:2,type:'worded',vc:'VC2M9A08d',q:'A train climbs with gradient 0.05. How far horizontally after rising 15 m?',a:'0.05 = 15/d → d = 300 m'},
      {tier:3,type:'show',vc:'VC2M9A08d',q:'Determine if (1,4), (3,8) and (5,12) are collinear.',a:'m(1→3) = 2, m(3→5) = 2. Equal gradients → collinear ✓'},
      {tier:4,type:'show',vc:'VC2M9A08d',q:'Find k if the line kx - 2y = 4 has gradient 3.',a:'2y = kx - 4 → y = (k/2)x - 2. So k/2 = 3 → k = 6.'},
    ]},

  { year:9, strand:'Algebra', topic:'Linear Graphs', skill:'Gradient-intercept form y = mx + c', vc:'VC2M9A08f',
    prereqs:['Gradient','y-intercept','Substitution'],
    btbEasy:'State the gradient and y-intercept of y = -3x + 7.',
    btbHard:'Line through (-2, 7) and (4, -5). Find equation, x-intercept and y-intercept.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A08f',q:'Gradient of y = 4x - 3',a:'4'},
      {tier:1,type:'std',vc:'VC2M9A08f',q:'y-intercept of y = 2x + 5',a:'5'},
      {tier:1,type:'tf',vc:'VC2M9A08f',q:'True or False: The point (0,3) lies on y = 2x + 3.',a:'True: 2(0) + 3 = 3'},
      {tier:1,type:'fill',vc:'VC2M9A08f',q:'Parallel lines have ___ gradients.',a:'equal'},
      {tier:2,type:'std',vc:'VC2M9A08f',q:'Write equation: m = 3, c = -2.',a:'y = 3x - 2'},
      {tier:2,type:'std',vc:'VC2M9A08f',q:'x-intercept of y = 4x - 12.',a:'x = 3'},
      {tier:2,type:'mc',vc:'VC2M9A08f',q:'Which line is parallel to y = 3x + 2?\nA) y = -3x + 2   B) y = 3x - 5   C) y = x + 3   D) y = 2x + 3',a:'B) y = 3x - 5 (same gradient)'},
      {tier:3,type:'show',vc:'VC2M9A08f',q:'Find equation through (1,5) and (3,9). Show steps.',a:'m = (9-5)/(3-1) = 2. y - 5 = 2(x-1) → y = 2x + 3. Check: 2(3)+3=9 ✓'},
      {tier:3,type:'fill',vc:'VC2M9A08f',q:'Perpendicular gradients multiply to give ___.',a:'-1'},
      {tier:3,type:'show',vc:'VC2M9A08f',q:'Are y = 3x + 1 and y = -x/3 - 2 perpendicular? Prove.',a:'Gradients: 3 and -1/3. Product = 3 × (-1/3) = -1. Yes, perpendicular ✓'},
      {tier:4,type:'show',vc:'VC2M9A08f',q:'Line through (-2,7) and (4,-5). Find equation and both intercepts.',a:'m = (-5-7)/(4-(-2)) = -2. y - 7 = -2(x+2) → y = -2x + 3. x-int: x=1.5; y-int: y=3.'},
      {tier:4,type:'show',vc:'VC2M9A08f',q:'Find perpendicular bisector of segment joining (2,4) and (6,8).',a:'Midpoint (4,6). Original m=1. Perp m=-1. y-6=-(x-4) → y=-x+10.'},
    ]},

  { year:9, strand:'Algebra', topic:'Linear Graphs', skill:'Finding the equation of a line', vc:'VC2M9A08g',
    prereqs:['Gradient-intercept form','Gradient from two points'],
    btbEasy:'Find equation through (0,-3) with gradient 2.',
    btbHard:'Lines AB: (1,3)(5,11) and CD: (2,9)(4,5). Find intersection.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A08g',q:'Equation through (0,4) with gradient 3.',a:'y = 3x + 4'},
      {tier:2,type:'std',vc:'VC2M9A08g',q:'Equation through (2,5) with gradient -1.',a:'y = -x + 7'},
      {tier:2,type:'std',vc:'VC2M9A08g',q:'Equation parallel to y = 2x - 1, through (3,0).',a:'y = 2x - 6'},
      {tier:3,type:'std',vc:'VC2M9A08g',q:'Midpoint of (2,4) and (6,8).',a:'(4,6)'},
      {tier:3,type:'worded',vc:'VC2M9A08g',q:'A line passes through (1,3) and (-2,-3). Find its equation.',a:'m = 6/3 = 2. y = 2x + 1.'},
      {tier:4,type:'show',vc:'VC2M9A08g',q:'Lines AB: (1,3)(5,11) and CD: (2,9)(4,5). Find intersection.',a:'AB: y=2x+1. CD: m=-2, y=-2x+13. Solve: 2x+1=-2x+13 → x=3, y=7. Point: (3,7).'},
    ]},

  // ═══════════════ CHAPTER 5: MEASUREMENT ═══════════════

  { year:9, strand:'Measurement', topic:'Perimeter and Area', skill:'Area of shapes', vc:'VC2M9M03d',
    prereqs:['Length and perimeter','Fractions'],
    btbEasy:'Find area of a triangle: base = 8 cm, height = 5 cm.',
    btbHard:'Find area of a sector with radius 6 cm and angle 120°. (2 d.p.)',
    questions:[
      {tier:1,type:'std',vc:'VC2M9M03d',q:'Area of a rectangle: 8 cm × 5 cm.',a:'40 cm²'},
      {tier:1,type:'std',vc:'VC2M9M03d',q:'Area of a triangle: b = 10, h = 6.',a:'30 cm²'},
      {tier:1,type:'std',vc:'VC2M9M03d',q:'Area of a circle: r = 5 cm. (1 d.p.)',a:'A = π × 25 ≈ 78.5 cm²'},
      {tier:2,type:'std',vc:'VC2M9M03d',q:'Area of a parallelogram: b = 12, h = 7.',a:'84 cm²'},
      {tier:2,type:'std',vc:'VC2M9M03d',q:'Area of a trapezium: parallel sides 5 and 9, height 4.',a:'½(5+9)(4) = 28 cm²'},
      {tier:2,type:'worded',vc:'VC2M9M03d',q:'A sector has radius 6 cm and angle 90°. Find its area.',a:'¼ × π × 36 ≈ 28.27 cm²'},
      {tier:3,type:'worded',vc:'VC2M9M03d',q:'A 10 m × 6 m room has a 3 m × 2 m tiled area cut out from a corner. Find net area.',a:'60 - 6 = 54 m²'},
      {tier:4,type:'show',vc:'VC2M9M03d',q:'A sector has area 30 cm². Its radius is 6 cm. Find the angle (1 d.p.).',a:'30 = (θ/360) × π × 36. θ = 30 × 360/(36π) ≈ 95.5°'},
    ]},

  { year:9, strand:'Measurement', topic:'Volume', skill:'Volume of prisms and cylinders', vc:'VC2M9M04c',
    prereqs:['Area of 2D shapes','Multiplication'],
    btbEasy:'Find volume of a rectangular prism: 4 × 5 × 3 cm.',
    btbHard:'A cylinder has volume 1000 cm³ and height 10 cm. Find its radius (2 d.p.).',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9M04c',q:'Volume of a prism = ___ × ___',a:'cross-sectional area × height (length)'},
      {tier:1,type:'std',vc:'VC2M9M04c',q:'Volume: rectangular prism 5 × 4 × 3.',a:'60 cm³'},
      {tier:1,type:'std',vc:'VC2M9M04c',q:'Volume of a cylinder: r = 3, h = 10. (2 d.p.)',a:'V = π × 9 × 10 ≈ 282.74 cm³'},
      {tier:2,type:'std',vc:'VC2M9M04c',q:'Volume: triangular prism, triangle base 6, height 4, length 10.',a:'V = ½(6)(4) × 10 = 120 cm³'},
      {tier:2,type:'worded',vc:'VC2M9M04c',q:'A cylindrical tank, r = 2 m, h = 3 m. Capacity in litres? (1 L = 1000 cm³)',a:'V = π(2²)(3) ≈ 37.70 m³ = 37 699 L'},
      {tier:3,type:'worded',vc:'VC2M9M04c',q:'Swimming pool: 25 m × 10 m. Depth: 1 m at shallow end, 2 m at deep end (trapezoidal cross-section). Volume?',a:'V = ½(1+2) × 25 × 10 = 375 m³'},
      {tier:4,type:'show',vc:'VC2M9M04c',q:'A cylinder has volume 1000 cm³ and height 10 cm. Find radius.',a:'πr²(10) = 1000 → r² = 100/π → r ≈ 5.64 cm'},
    ]},

  // ═══════════════ CHAPTER 6: INDICES AND SURDS ═══════════════

  { year:9, strand:'Number', topic:'Indices', skill:'Index laws — multiplication and division', vc:'VC2M9N11b',
    prereqs:['Index notation','Multiplication of integers'],
    btbEasy:'Simplify: 2x³ × 3x⁴',
    btbHard:'Simplify: (2x²y³)³ ÷ (4x³y²)',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9N11b',q:'When multiplying same base, ___ the indices.',a:'add'},
      {tier:1,type:'fill',vc:'VC2M9N11b',q:'When dividing same base, ___ the indices.',a:'subtract'},
      {tier:1,type:'std',vc:'VC2M9N11b',q:'Simplify: 7² × 7⁴',a:'7⁶'},
      {tier:1,type:'std',vc:'VC2M9N11b',q:'Simplify: x⁴ × x³',a:'x⁷'},
      {tier:1,type:'std',vc:'VC2M9N11b',q:'Simplify: a⁶ ÷ a⁴',a:'a²'},
      {tier:2,type:'std',vc:'VC2M9N11b',q:'Simplify: 2x² × 3x³',a:'6x⁵'},
      {tier:2,type:'std',vc:'VC2M9N11b',q:'Simplify: 12a⁴ ÷ 4a²',a:'3a²'},
      {tier:2,type:'std',vc:'VC2M9N11b',q:'Write missing number: 2⁷ × 2□ = 2¹⁹',a:'12'},
      {tier:2,type:'std',vc:'VC2M9N11b',q:'Evaluate without calculator: 7⁷ ÷ 7⁵',a:'7² = 49'},
      {tier:3,type:'error',vc:'VC2M9N11b',q:'Jake writes: 3² × 3³ = 9⁵. Find his error.',a:'He multiplied the bases too. Correct: same base, add indices: 3⁵ = 243'},
      {tier:3,type:'show',vc:'VC2M9N11b',q:'Simplify (4x²)³ ÷ (8x³). Show all steps.',a:'64x⁶ ÷ 8x³ = 8x³'},
      {tier:4,type:'show',vc:'VC2M9N11b',q:'Simplify: (2x²y³)³ ÷ (4x³y²). Show full working.',a:'8x⁶y⁹ ÷ 4x³y² = 2x³y⁷'},
    ]},

  { year:9, strand:'Number', topic:'Indices', skill:'Index laws — zero and negative indices', vc:'VC2M9N11e',
    prereqs:['Index laws multiplication and division'],
    btbEasy:'Evaluate: 5⁰ + 2⁻³',
    btbHard:'Simplify and write with positive indices: (3x⁻²y)² ÷ (9x⁻³)',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N11e',q:'Evaluate: x⁰',a:'1 (for x ≠ 0)'},
      {tier:1,type:'std',vc:'VC2M9N11e',q:'Evaluate: 4⁰',a:'1'},
      {tier:1,type:'std',vc:'VC2M9N11e',q:'Evaluate: 2⁻³',a:'1/8'},
      {tier:2,type:'std',vc:'VC2M9N11e',q:'Write with positive index: x⁻⁴',a:'1/x⁴'},
      {tier:2,type:'std',vc:'VC2M9N11e',q:'Evaluate: 3⁻²',a:'1/9'},
      {tier:2,type:'std',vc:'VC2M9N11e',q:'Simplify: (2x⁻³)(4x²)',a:'8x⁻¹ = 8/x'},
      {tier:3,type:'show',vc:'VC2M9N11e',q:'Solve: 2ˣ = 32',a:'2ˣ = 2⁵ → x = 5'},
      {tier:3,type:'show',vc:'VC2M9N11e',q:'Prove that a⁰ = 1 using index laws.',a:'aⁿ ÷ aⁿ = a⁰; also aⁿ ÷ aⁿ = 1. Therefore a⁰ = 1 ✓'},
      {tier:4,type:'show',vc:'VC2M9N11e',q:'Solve: 4ˣ = 8 by expressing both as powers of 2.',a:'2²ˣ = 2³ → 2x = 3 → x = 3/2'},
    ]},

  { year:9, strand:'Number', topic:'Scientific Notation', skill:'Scientific notation', vc:'VC2M9N12a',
    prereqs:['Index notation','Negative indices','Multiplying by powers of 10'],
    btbEasy:'Write 45 300 000 in scientific notation.',
    btbHard:'Calculate (3.6 × 10⁴) × (2.5 × 10⁻⁷). Give answer in scientific notation.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9N12a',q:'Write in scientific notation: 45 000',a:'4.5 × 10⁴'},
      {tier:1,type:'std',vc:'VC2M9N12a',q:'Write in scientific notation: 0.0052',a:'5.2 × 10⁻³'},
      {tier:1,type:'std',vc:'VC2M9N12a',q:'Write as a basic numeral: 3.8 × 10⁵',a:'380 000'},
      {tier:2,type:'std',vc:'VC2M9N12a',q:'Write in scientific notation: 0.000 47',a:'4.7 × 10⁻⁴'},
      {tier:2,type:'std',vc:'VC2M9N12a',q:'Calculate: (4 × 10³) × (2 × 10⁴)',a:'8 × 10⁷'},
      {tier:2,type:'std',vc:'VC2M9N12a',q:'Calculate: (9 × 10⁶) ÷ (3 × 10²)',a:'3 × 10⁴'},
      {tier:3,type:'worded',vc:'VC2M9N12a',q:'Light travels 3 × 10⁸ m/s. How far in 5 minutes?',a:'5 × 60 × 3×10⁸ = 9 × 10¹⁰ m'},
      {tier:3,type:'std',vc:'VC2M9N12a',q:'Order from smallest: 3.2 × 10⁻³, 2.1 × 10⁻², 8.4 × 10⁻⁴',a:'8.4×10⁻⁴, 3.2×10⁻³, 2.1×10⁻²'},
      {tier:4,type:'worded',vc:'VC2M9N12a',q:'The Sun is 1.5 × 10¹¹ m from Earth. Light travels 3 × 10⁸ m/s. How many minutes does it take light to reach Earth?',a:'t = 1.5×10¹¹ / 3×10⁸ = 500 s ≈ 8.33 minutes'},
    ]},

  // ═══════════════ CHAPTER 7: GEOMETRY ═══════════════

  { year:9, strand:'Geometry', topic:'Angles', skill:'Angles and triangles — proofs and reasoning', vc:'VC2M9SP01a',
    prereqs:['Angle types','Parallel lines basics'],
    btbEasy:'Find the value of a: triangle with angles 55°, 72° and a°.',
    btbHard:'Exterior angle of triangle = 115°. One non-adjacent interior angle = 48°. Find the other.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9SP01a',q:'Angles in a triangle sum to ___°',a:'180°'},
      {tier:1,type:'std',vc:'VC2M9SP01a',q:'Angles in a straight line sum to ___°',a:'180°'},
      {tier:1,type:'std',vc:'VC2M9SP01a',q:'Triangle angles: 40° and 75°. Find third angle.',a:'65°'},
      {tier:2,type:'worded',vc:'VC2M9SP01a',q:'An exterior angle of a triangle is 115°. One non-adjacent interior angle is 48°. Find the other.',a:'115° - 48° = 67°'},
      {tier:2,type:'std',vc:'VC2M9SP01a',q:'Isosceles triangle. One angle = 110°. Find the equal base angles.',a:'(180 - 110)/2 = 35° each'},
      {tier:3,type:'show',vc:'VC2M9SP01a',q:'Prove that the exterior angle of a triangle equals the sum of the two non-adjacent interior angles.',a:'Exterior angle + adjacent interior = 180° (straight line). All 3 interior angles = 180°. By substitution, exterior angle = sum of other two interior angles.'},
      {tier:4,type:'std',vc:'VC2M9SP01a',q:'Sum of interior angles of a polygon with n sides = ___.',a:'(n - 2) × 180°'},
    ]},

  { year:9, strand:'Geometry', topic:'Polygons', skill:'Quadrilaterals and polygons', vc:'VC2M9SP01c',
    prereqs:['Angle sum in triangles','Properties of quadrilaterals'],
    btbEasy:'Find angle sum of a hexagon.',
    btbHard:'Regular polygon has interior angles of 156°. How many sides?',
    questions:[
      {tier:1,type:'std',vc:'VC2M9SP01c',q:'Angle sum of a quadrilateral.',a:'360°'},
      {tier:1,type:'std',vc:'VC2M9SP01c',q:'Angle sum of a pentagon.',a:'540°'},
      {tier:2,type:'std',vc:'VC2M9SP01c',q:'Regular hexagon: interior angle size.',a:'(6-2)×180/6 = 120°'},
      {tier:2,type:'worded',vc:'VC2M9SP01c',q:'Calculate number of sides of polygon with angle sum 2520°.',a:'(n-2)×180 = 2520 → n = 16'},
      {tier:3,type:'worded',vc:'VC2M9SP01c',q:'Quadrilateral ABCD: angles A=2x°, B=3x°, C=4x°, D=3x°. Find each angle.',a:'12x = 360 → x = 30. Angles: 60°, 90°, 120°, 90°.'},
      {tier:4,type:'show',vc:'VC2M9SP01c',q:'Regular polygon has interior angles of 156°. How many sides?',a:'Exterior angle = 24°. n = 360/24 = 15 sides.'},
    ]},

  { year:9, strand:'Geometry', topic:'Congruence', skill:'Congruent triangles', vc:'VC2M9SP02a',
    prereqs:['Triangle properties','Angle and length matching'],
    btbEasy:'Name the congruence condition: two sides and the included angle are equal.',
    btbHard:'Prove two triangles are congruent using ASA, then find an unknown length.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9SP02a',q:'The four congruence conditions are: SSS, ___, ___, RHS.',a:'SAS, AAS (or ASA)'},
      {tier:1,type:'mc',vc:'VC2M9SP02a',q:'Two triangles have all three sides equal. Condition:\nA) SSS   B) SAS   C) AAS   D) RHS',a:'A) SSS'},
      {tier:2,type:'std',vc:'VC2M9SP02a',q:'Two triangles: 2 sides equal and the included angle equal. Condition?',a:'SAS (Side-Angle-Side)'},
      {tier:2,type:'std',vc:'VC2M9SP02a',q:'Two triangles: hypotenuse and one side equal (right triangles). Condition?',a:'RHS (Right-Hypotenuse-Side)'},
      {tier:3,type:'show',vc:'VC2M9SP02a',q:'ABCD is a square. Prove triangle ABD ≅ triangle CBD.',a:'AB = CB (sides of square), BD = BD (common), AD = CD (sides of square) → SSS ✓'},
      {tier:4,type:'show',vc:'VC2M9SP02a',q:'In triangle PQR and triangle XYZ: PQ = XY, angle P = angle X, angle Q = angle Y. Prove they are congruent and explain which condition applies.',a:'AAS: two angles and a corresponding side equal → congruent.'},
    ]},

  { year:9, strand:'Geometry', topic:'Similarity', skill:'Similar triangles and applications', vc:'VC2M9SP03b',
    prereqs:['Congruence conditions','Ratios and scale factors'],
    btbEasy:'Two triangles are similar with scale factor 3. Shortest side of small = 4 cm. Find corresponding side of large.',
    btbHard:'A 1.8 m person casts a 2.4 m shadow. Nearby tree casts 8 m shadow. Height of tree?',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9SP03b',q:'Similar figures have the same ___ but different ___.',a:'shape (angles); size (sides)'},
      {tier:2,type:'std',vc:'VC2M9SP03b',q:'Two similar triangles. Scale factor = 2. Smaller has side 5 cm. Larger has corresponding side?',a:'10 cm'},
      {tier:2,type:'worded',vc:'VC2M9SP03b',q:'A 1.8 m person casts 2.4 m shadow. Nearby tree casts 8 m shadow. Height of tree?',a:'1.8/2.4 = h/8 → h = 6 m'},
      {tier:3,type:'show',vc:'VC2M9SP03b',q:'Map scale 1:50 000. Two towns 4.5 cm apart on map. Real distance?',a:'4.5 × 50 000 = 225 000 cm = 2.25 km'},
      {tier:3,type:'show',vc:'VC2M9SP03b',q:'Two triangles: angles 40°, 60°, 80° in both. Are they similar? What condition?',a:'AAA (or AA): all angles equal → similar triangles ✓'},
      {tier:4,type:'worded',vc:'VC2M9SP03b',q:'Similar triangles: small has sides 3, 4, 5. Large has perimeter 36. Find sides of large.',a:'Scale factor = 36/12 = 3. Sides: 9, 12, 15.'},
    ]},

  // ═══════════════ CHAPTER 8: ALGEBRAIC TECHNIQUES ═══════════════

  { year:9, strand:'Algebra', topic:'Expanding and Factorising', skill:'Expanding binomial products', vc:'VC2M9A09a',
    prereqs:['Expanding single brackets','Like terms'],
    btbEasy:'Expand: (x + 3)(x + 5)',
    btbHard:'Expand and simplify: (3x - 2)(4x + 5) - 2(x - 1)²',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A09a',q:'Expand: (x + 2)(x + 5)',a:'x² + 7x + 10'},
      {tier:1,type:'std',vc:'VC2M9A09a',q:'Expand: (b + 3)(b + 4)',a:'b² + 7b + 12'},
      {tier:1,type:'std',vc:'VC2M9A09a',q:'Expand: (x + 3)(x - 4)',a:'x² - x - 12'},
      {tier:2,type:'std',vc:'VC2M9A09a',q:'Expand: (4x + 3)(2x + 5)',a:'8x² + 26x + 15'},
      {tier:2,type:'std',vc:'VC2M9A09a',q:'Expand: (3x - 2)(3x + 5)',a:'9x² + 9x - 10'},
      {tier:2,type:'worded',vc:'VC2M9A09a',q:'A rectangular room 4 m × 5 m is extended by x m on both sides. Find expanded expression for new area.',a:'(4+x)(5+x) = x² + 9x + 20 m²'},
      {tier:3,type:'std',vc:'VC2M9A09a',q:'Find missing term: (x + 2)(x + ?) = x² + 5x + 6',a:'(x + 2)(x + 3) = x² + 5x + 6; missing term = 3'},
      {tier:3,type:'worded',vc:'VC2M9A09a',q:'A rectangular picture frame 5 cm wide. Length = 2x, width = x. Express the area of the picture only (inside frame) in expanded form.',a:'(2x-10)(x-10) = 2x² - 30x + 100'},
      {tier:4,type:'show',vc:'VC2M9A09a',q:'Expand (x + 1)(x + 2)(x + 3). Show all steps.',a:'First: (x+1)(x+2) = x²+3x+2. Then: (x²+3x+2)(x+3) = x³+3x²+3x²+9x+2x+6 = x³+6x²+11x+6'},
    ]},

  { year:9, strand:'Algebra', topic:'Expanding and Factorising', skill:'Perfect squares and difference of two squares', vc:'VC2M9A09b',
    prereqs:['Expanding binomial products'],
    btbEasy:'Expand: (x + 5)²',
    btbHard:'Factorise: 16x² - 49y²',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A09b',q:'Expand: (x + 3)²',a:'x² + 6x + 9'},
      {tier:1,type:'std',vc:'VC2M9A09b',q:'Expand: (x - 4)²',a:'x² - 8x + 16'},
      {tier:1,type:'std',vc:'VC2M9A09b',q:'Expand: (x + 3)(x - 3)',a:'x² - 9 (DOTS)'},
      {tier:2,type:'std',vc:'VC2M9A09b',q:'Expand: (3x - 2)(3x + 2)',a:'9x² - 4'},
      {tier:2,type:'std',vc:'VC2M9A09b',q:'Expand: (5x - 4)(5x + 4)',a:'25x² - 16'},
      {tier:2,type:'std',vc:'VC2M9A09b',q:'Expand: (2x + 3)²',a:'4x² + 12x + 9'},
      {tier:3,type:'worded',vc:'VC2M9A09b',q:'Lara is x years old. Her friends are (x-2) and (x+2) years old. Is x² equal to the product of the friends\' ages? Explain.',a:'(x-2)(x+2) = x² - 4 ≠ x². Not equal; it is 4 less.'},
      {tier:3,type:'show',vc:'VC2M9A09b',q:'Calculate 29 × 31 using the difference of two squares.',a:'(30-1)(30+1) = 900 - 1 = 899'},
      {tier:4,type:'std',vc:'VC2M9A09b',q:'Factorise: 16x² - 49y²',a:'(4x + 7y)(4x - 7y)'},
    ]},

  { year:9, strand:'Algebra', topic:'Expanding and Factorising', skill:'Factorising monic quadratic trinomials', vc:'VC2M9A09f',
    prereqs:['Expanding binomial products','DOTS and perfect squares'],
    btbEasy:'Factorise: x² + 7x + 12',
    btbHard:'Factorise completely: 2x² + 8x - 24',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A09f',q:'Factorise: x² + 3x - 4',a:'(x + 4)(x - 1)'},
      {tier:1,type:'std',vc:'VC2M9A09f',q:'Factorise: x² - 6x + 5',a:'(x - 1)(x - 5)'},
      {tier:1,type:'std',vc:'VC2M9A09f',q:'Factorise: x² - 7x - 8',a:'(x - 8)(x + 1)'},
      {tier:2,type:'std',vc:'VC2M9A09f',q:'Factorise: x² - 9x + 8',a:'(x - 1)(x - 8)'},
      {tier:2,type:'std',vc:'VC2M9A09f',q:'Factorise by first taking out HCF: 2x² + 10x + 8',a:'2(x + 1)(x + 4)'},
      {tier:2,type:'std',vc:'VC2M9A09f',q:'Factorise: x² + 6x + 9',a:'(x + 3)² — perfect square trinomial'},
      {tier:3,type:'worded',vc:'VC2M9A09f',q:'A rectangle has area x² + 8x + 15. Write expressions for its possible dimensions.',a:'(x + 3) and (x + 5)'},
      {tier:3,type:'std',vc:'VC2M9A09f',q:'Factorise: x² - 6x + 9 — what type is it?',a:'(x - 3)² — a perfect square trinomial'},
      {tier:4,type:'show',vc:'VC2M9A09f',q:'Write x² - 6x + 2 in completed square form (x + b)² + c.',a:'(x-3)² - 9 + 2 = (x-3)² - 7'},
    ]},

  { year:9, strand:'Algebra', topic:'Expanding and Factorising', skill:'Factorising by grouping in pairs', vc:'VC2M9A09e',
    prereqs:['Factorising HCF','Factorising trinomials'],
    btbEasy:'Factorise: x² + 3x + 2x + 6 by grouping.',
    btbHard:'Factorise: 2x² - 9 - 18x + x',
    questions:[
      {tier:1,type:'std',vc:'VC2M9A09e',q:'Factorise by grouping: x² + 3x + 2x + 6',a:'x(x+3) + 2(x+3) = (x+2)(x+3)'},
      {tier:1,type:'std',vc:'VC2M9A09e',q:'Factorise by grouping: x² + 4x + 3x + 12',a:'x(x+4) + 3(x+4) = (x+3)(x+4)'},
      {tier:2,type:'std',vc:'VC2M9A09e',q:'Factorise by grouping: x² - 6x + 4x - 24',a:'x(x-6) + 4(x-6) = (x+4)(x-6)'},
      {tier:2,type:'std',vc:'VC2M9A09e',q:'Factorise: 3ab + 5bc + 3ad + 5cd',a:'b(3a+5c) + d(3a+5c) = (b+d)(3a+5c)'},
      {tier:3,type:'std',vc:'VC2M9A09e',q:'Factorise: x² - ax + x - a (use factor of 1)',a:'x(x-a) + 1(x-a) = (x+1)(x-a)'},
      {tier:4,type:'show',vc:'VC2M9A09e',q:'Factorise: 2x² - 9 - 18x + x (first rearrange).',a:'2x² + x - 18x - 9 = x(2x+1) - 9(2x+1) = (x-9)(2x+1)'},
    ]},

  // ═══════════════ CHAPTER 9: PROBABILITY AND STATISTICS ═══════════════

  { year:9, strand:'Statistics', topic:'Probability', skill:'Review of probability — sample spaces and events', vc:'VC2M9P01a',
    prereqs:['Fractions','Listing outcomes'],
    btbEasy:'A letter is chosen from ALPHABET. Find P(A).',
    btbHard:'Card drawn from deck. Find P(red king or black ace).',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9P01a',q:'P(certain event) = ___',a:'1'},
      {tier:1,type:'fill',vc:'VC2M9P01a',q:'P(impossible event) = ___',a:'0'},
      {tier:1,type:'std',vc:'VC2M9P01a',q:'A six-sided die is rolled. P(3) = ?',a:'1/6'},
      {tier:1,type:'std',vc:'VC2M9P01a',q:'P(rolling even number on a die) = ?',a:'3/6 = 1/2'},
      {tier:2,type:'std',vc:'VC2M9P01a',q:'A letter chosen from ALPHABET. Find P(vowel).',a:'Vowels: A, E, A. P = 3/8'},
      {tier:2,type:'worded',vc:'VC2M9P01a',q:'A card is drawn from a deck of 52. Find P(ace).',a:'4/52 = 1/13'},
      {tier:2,type:'worded',vc:'VC2M9P01a',q:'A six-sided die: P(number greater than 4) = ?',a:'2/6 = 1/3'},
      {tier:3,type:'worded',vc:'VC2M9P01a',q:'A swimming pool has 8 lanes, each swimmer equally likely in any lane. P(swimmer is NOT in lane 1)?',a:'7/8'},
      {tier:3,type:'worded',vc:'VC2M9P01a',q:'A card deck has 13 black spades, 13 black clubs, 13 red hearts, 13 red diamonds. P(red king or black ace)?',a:'P = 2/52 + 2/52 = 4/52 = 1/13'},
      {tier:4,type:'show',vc:'VC2M9P01a',q:'School captain chosen from 4 candidates: Hayley(18), Rocco(18), Alisa(17), Stuart(17). List sample space. P(17-year-old wins)?',a:'S = {H, R, A, S}. P = 2/4 = 1/2.'},
    ]},

  { year:9, strand:'Statistics', topic:'Probability', skill:'Venn diagrams and two-way tables', vc:'VC2M9P01b',
    prereqs:['Probability basics','Set notation'],
    btbEasy:'In a class of 30, 18 play sport, 14 play music, 8 play both. How many play neither?',
    btbHard:'P(A) = 0.4, P(B) = 0.5, P(A ∩ B) = 0.2. Find P(A ∪ B) and P(A only).',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9P01b',q:'P(A or B) for mutually exclusive events = P(A) + ___',a:'P(B)'},
      {tier:2,type:'worded',vc:'VC2M9P01b',q:'Class of 30: 18 play sport (S), 14 play music (M), 8 play both. Draw a Venn diagram and find P(plays only sport).',a:'Only S = 18-8 = 10. P = 10/30 = 1/3'},
      {tier:2,type:'std',vc:'VC2M9P01b',q:'P(A) = 0.4, P(B) = 0.3, mutually exclusive. P(A or B) = ?',a:'0.7'},
      {tier:3,type:'show',vc:'VC2M9P01b',q:'P(A) = 0.4, P(B) = 0.5, P(A ∩ B) = 0.2. Find P(A ∪ B).',a:'P(A∪B) = P(A) + P(B) - P(A∩B) = 0.4 + 0.5 - 0.2 = 0.7'},
      {tier:4,type:'show',vc:'VC2M9P01b',q:'P(A) + P(B) = 1.1. Can A and B be mutually exclusive? Why?',a:'No — mutually exclusive requires P(A∪B) = P(A)+P(B) which would exceed 1. Impossible.'},
    ]},

  { year:9, strand:'Statistics', topic:'Probability', skill:'Two-step experiments — arrays and tree diagrams', vc:'VC2M9P02a',
    prereqs:['Sample spaces','Basic probability'],
    btbEasy:'Two dice rolled. P(sum = 7) = ?',
    btbHard:'Bag: 4 red, 6 blue. Draw 2 without replacement. P(different colours)?',
    questions:[
      {tier:1,type:'std',vc:'VC2M9P02a',q:'Two coins flipped. P(both heads) = ?',a:'1/4'},
      {tier:2,type:'std',vc:'VC2M9P02a',q:'Two dice rolled. P(sum = 7) = ?',a:'6/36 = 1/6'},
      {tier:2,type:'std',vc:'VC2M9P02a',q:'Two dice rolled. P(sum > 10) = ?',a:'3/36 = 1/12'},
      {tier:2,type:'mc',vc:'VC2M9P02a',q:'Two cards without replacement. P(2 aces) =\nA) 4/52 × 4/51   B) 4/52 × 3/51   C) 4/52 × 4/52   D) 1/13 × 1/13',a:'B) 4/52 × 3/51 = 1/221'},
      {tier:3,type:'show',vc:'VC2M9P02a',q:'Red bag: 3R, 2B. Blue bag: 1R, 4B. Choose bag randomly then draw. P(red ball)?',a:'½ × 3/5 + ½ × 1/5 = 3/10 + 1/10 = 2/5'},
      {tier:4,type:'show',vc:'VC2M9P02a',q:'Bag: 4 red, 6 blue. Draw 2 without replacement. P(different colours)?',a:'P(RB) + P(BR) = (4/10)(6/9) + (6/10)(4/9) = 48/90 = 8/15'},
    ]},

  { year:9, strand:'Statistics', topic:'Data', skill:'Mean, median and mode', vc:'VC2M9D01b',
    prereqs:['Averages basics','Ordering data'],
    btbEasy:'Find mean, median and mode of: 3, 7, 8, 8, 9, 13.',
    btbHard:'Dataset: 5, 8, 8, 12, 15, 19, 52. Is 52 an outlier? Compare mean with and without it.',
    questions:[
      {tier:1,type:'std',vc:'VC2M9D01b',q:'Mean of 2, 4, 6, 8.',a:'5'},
      {tier:1,type:'std',vc:'VC2M9D01b',q:'Median of 1, 3, 5, 7, 9.',a:'5'},
      {tier:1,type:'mc',vc:'VC2M9D01b',q:'Which average is most affected by outliers?\nA) Median   B) Mode   C) Mean   D) Range',a:'C) Mean'},
      {tier:2,type:'std',vc:'VC2M9D01b',q:'Find mean, median and mode of: 14, 16, 14, 15, 12, 16, 17, 16, 15.',a:'Mean ≈ 15, Median = 15, Mode = 16'},
      {tier:2,type:'worded',vc:'VC2M9D01b',q:'7 numbers have a mean of 8. Six are: 9, 7, 6, 4, 11, 10. Find the 7th.',a:'Sum = 56. Known sum = 47. 7th = 9.'},
      {tier:3,type:'show',vc:'VC2M9D01b',q:'Dataset: 5, 8, 8, 12, 15, 19, 52. Find mean with and without 52.',a:'With: 119/7 ≈ 17.0. Without: 67/6 ≈ 11.2. Outlier raises mean by ~5.8.'},
      {tier:3,type:'worded',vc:'VC2M9D01b',q:'Groups: n=10 mean=70, n=15 mean=80. Combined mean?',a:'(700+1200)/25 = 76'},
      {tier:3,type:'error',vc:'VC2M9D01b',q:'Rosa says: "The mean is always the best measure of centre." Give an example where the median is better.',a:'House prices: a few expensive houses skew the mean far above the typical price. Median better represents the "middle" house.'},
      {tier:4,type:'worded',vc:'VC2M9D01b',q:'4 tests average 72%. Need 80% average over 5 tests. What score needed on test 5?',a:'5×80 = 400. 4×72 = 288. Need 112% — impossible.'},
    ]},

  { year:9, strand:'Statistics', topic:'Data', skill:'Measures of spread — range and interquartile range', vc:'VC2M9D01e',
    prereqs:['Mean median mode','Ordering data'],
    btbEasy:'Find IQR of: 3, 5, 7, 9, 11, 13, 15.',
    btbHard:'Determine whether 52 is an outlier in: 5, 8, 8, 12, 15, 19, 52 using the IQR method.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M9D01e',q:'IQR = Q3 - ___',a:'Q1'},
      {tier:1,type:'std',vc:'VC2M9D01e',q:'Range of: 4, 7, 2, 9, 5.',a:'9 - 2 = 7'},
      {tier:2,type:'std',vc:'VC2M9D01e',q:'Find IQR: Q1 = 8, Q3 = 20.',a:'IQR = 12'},
      {tier:2,type:'std',vc:'VC2M9D01e',q:'5-number summary for: 3, 5, 7, 9, 11, 13, 15.',a:'Min=3, Q1=5, Median=9, Q3=13, Max=15'},
      {tier:3,type:'show',vc:'VC2M9D01e',q:'Dataset: 5, 8, 8, 12, 15, 19, 52. Is 52 an outlier? Show working.',a:'Q1=8, Q3=19, IQR=11. Upper fence = 19 + 1.5(11) = 35.5. Since 52 > 35.5, yes it\'s an outlier.'},
      {tier:4,type:'show',vc:'VC2M9D01e',q:'Prove that adding constant k to all values shifts median by k but does not change IQR.',a:'New Q1 = Q1+k, New Q3 = Q3+k. IQR = (Q3+k)-(Q1+k) = Q3-Q1. Unchanged ✓. New median = old median+k ✓'},
    ]},

  // ═══════════════ CHAPTER 10: QUADRATIC EQUATIONS AND GRAPHS ═══════════════

  { year:9, strand:'Algebra', topic:'Quadratic Equations', skill:'Solving quadratic equations ax² + bx = 0', vc:'VC2M10A01a',
    prereqs:['Factorising HCF','Null factor law'],
    btbEasy:'Solve: 2x² - 6x = 0',
    btbHard:'Solve: 9x² = 16 by writing as perfect square.',
    questions:[
      {tier:1,type:'fill',vc:'VC2M10A01a',q:'Null factor law: if ab = 0, then a = ___ or b = ___',a:'0 or 0'},
      {tier:1,type:'std',vc:'VC2M10A01a',q:'Solve: x(x + 5) = 0',a:'x = 0 or x = -5'},
      {tier:1,type:'std',vc:'VC2M10A01a',q:'Solve: x² = 25',a:'x = ±5'},
      {tier:2,type:'std',vc:'VC2M10A01a',q:'Solve: 2x² - 6x = 0',a:'2x(x-3) = 0 → x = 0 or x = 3'},
      {tier:2,type:'std',vc:'VC2M10A01a',q:'Solve: 3x² = 12x',a:'3x(x-4) = 0 → x = 0 or x = 4'},
      {tier:2,type:'std',vc:'VC2M10A01a',q:'Solve: x² - 144 = 0',a:'x = ±12'},
      {tier:3,type:'worded',vc:'VC2M10A01a',q:'The product of x and a number 3 more than x is zero. Find x.',a:'x(x+3)=0 → x=0 or x=-3'},
      {tier:3,type:'show',vc:'VC2M10A01a',q:'Explain why x² + 4 = 0 has no real solutions.',a:'x² ≥ 0 for all real x, so x² + 4 ≥ 4 > 0. Can never equal zero.'},
      {tier:4,type:'std',vc:'VC2M10A01a',q:'Solve: 25x² = 36',a:'x² = 36/25 → x = ±6/5'},
    ]},

  { year:9, strand:'Algebra', topic:'Quadratic Equations', skill:'Solving x² + bx + c = 0 by factorising', vc:'VC2M10A01b',
    prereqs:['Factorising monic trinomials','Null factor law'],
    btbEasy:'Solve: x² + 5x + 6 = 0',
    btbHard:'Find values of b such that x² + bx + 16 = 0 has exactly one solution.',
    questions:[
      {tier:1,type:'std',vc:'VC2M10A01b',q:'Solve: x² + 5x + 6 = 0',a:'(x+2)(x+3)=0 → x=-2 or x=-3'},
      {tier:1,type:'std',vc:'VC2M10A01b',q:'Solve: x² - 7x + 10 = 0',a:'(x-2)(x-5)=0 → x=2 or x=5'},
      {tier:1,type:'std',vc:'VC2M10A01b',q:'Solve: x² - 9 = 0',a:'x = ±3'},
      {tier:2,type:'std',vc:'VC2M10A01b',q:'Solve: x² + 2x - 8 = 0',a:'(x+4)(x-2)=0 → x=-4 or x=2'},
      {tier:2,type:'std',vc:'VC2M10A01b',q:'Solve: x² + 6x + 9 = 0',a:'(x+3)²=0 → x=-3 (one repeated solution)'},
      {tier:2,type:'worded',vc:'VC2M10A01b',q:'The product of an integer and one less than the same integer is 6. Write and solve.',a:'x(x-1)=6 → x²-x-6=0 → (x-3)(x+2)=0 → x=3 or x=-2'},
      {tier:3,type:'worded',vc:'VC2M10A01b',q:'Rectangle: length is 3 more than width, area = 54 cm². Find dimensions.',a:'w(w+3)=54 → w²+3w-54=0 → (w+9)(w-6)=0 → w=6, l=9'},
      {tier:3,type:'show',vc:'VC2M10A01b',q:'Sum of first n integers = n(n+1)/2. Solve for n if sum = 45.',a:'n(n+1)/2 = 45 → n²+n-90=0 → (n-9)(n+10)=0 → n=9 (positive)'},
      {tier:4,type:'worded',vc:'VC2M10A01b',q:'Find b such that x² + bx + 16 = 0 has exactly one solution.',a:'Discriminant = 0: b²-64=0 → b=±8'},
    ]},

  { year:9, strand:'Algebra', topic:'Parabolas', skill:'The parabola y = x² and transformations', vc:'VC2M10A02a',
    prereqs:['Plotting coordinates','Quadratic equations'],
    btbEasy:'State vertex, axis of symmetry and direction for y = x² - 4.',
    btbHard:'Sketch y = -2(x-1)² + 8. State all key features.',
    questions:[
      {tier:1,type:'mc',vc:'VC2M10A02a',q:'The graph of y = x² is called a:\nA) Straight line   B) Parabola   C) Hyperbola   D) Circle',a:'B) Parabola'},
      {tier:1,type:'std',vc:'VC2M10A02a',q:'Vertex of y = x²?',a:'(0, 0)'},
      {tier:1,type:'mc',vc:'VC2M10A02a',q:'Does y = -x² open:\nA) Up   B) Down   C) Left   D) Right',a:'B) Down'},
      {tier:2,type:'std',vc:'VC2M10A02a',q:'Axis of symmetry of y = x² - 6x + 5.',a:'x = 3'},
      {tier:2,type:'std',vc:'VC2M10A02a',q:'y-intercept of y = x² - 6x + 5.',a:'(0, 5)'},
      {tier:2,type:'std',vc:'VC2M10A02a',q:'x-intercepts of y = x² - 6x + 5.',a:'x = 1 and x = 5'},
      {tier:3,type:'show',vc:'VC2M10A02a',q:'Find vertex of y = 2x² - 8x + 5.',a:'x = 8/(2×2) = 2. y = 8-16+5 = -3. Vertex: (2, -3).'},
      {tier:3,type:'worded',vc:'VC2M10A02a',q:'Ball thrown: h = -5t² + 20t + 1. Maximum height and when?',a:'t = 20/(2×5) = 2 s. h = -20+40+1 = 21 m.'},
      {tier:4,type:'show',vc:'VC2M10A02a',q:'Sketch y = -2(x-1)² + 8. State vertex, x-intercepts, y-intercept and direction.',a:'Vertex (1,8). Opens down. x-ints: -2(x-1)²=-8 → (x-1)²=4 → x=3 or x=-1. y-int: -2(1)+8=6.'},
      {tier:4,type:'worded',vc:'VC2M10A02a',q:'For what values of k does y = x² + 4x + k have no real zeros?',a:'Discriminant < 0: 16-4k < 0 → k > 4.'},
    ]},

  { year:9, strand:'Algebra', topic:'Parabolas', skill:'Sketching parabolas using intercept form', vc:'VC2M10A02d',
    prereqs:['Factorising quadratics','Parabola basics'],
    btbEasy:'Sketch y = (x-2)(x+4). State x-intercepts and vertex.',
    btbHard:'Find equation of parabola with x-intercepts at -1 and 5, passing through (0, 10).',
    questions:[
      {tier:1,type:'std',vc:'VC2M10A02d',q:'x-intercepts of y = x(x-4).',a:'x = 0 and x = 4'},
      {tier:2,type:'std',vc:'VC2M10A02d',q:'x-intercepts of y = (x+2)(x-3).',a:'x = -2 and x = 3'},
      {tier:2,type:'std',vc:'VC2M10A02d',q:'Axis of symmetry of y = (x+2)(x-3).',a:'x = ½(-2+3) = 0.5'},
      {tier:3,type:'show',vc:'VC2M10A02d',q:'Find where y = x² and y = x + 6 intersect.',a:'x²=x+6 → x²-x-6=0 → (x-3)(x+2)=0 → points (3,9) and (-2,4)'},
      {tier:4,type:'show',vc:'VC2M10A02d',q:'Find equation of parabola through (0,3), (1,0) and (3,0).',a:'y = a(x-1)(x-3). At (0,3): 3=a(3) → a=1. y = (x-1)(x-3) = x²-4x+3.'},
    ]},
]

// Export count for verification
export const CAMBRIDGE_Y9_COUNT = CAMBRIDGE_Y9.reduce((sum, s) => sum + s.questions.length, 0)
