// All questions stored as JSON objects — no single-quote string issues
// This data is seeded to Supabase on first run via seedCurriculum()

export const CURRICULUM = [
  // ── YEAR 5 ──
  { year: 5, strand: "Number", topic: "Whole Numbers", skill: "Place value to millions", vc: "VC2M5N01",
    prereqs: ["Counting", "Place value to thousands"],
    btbEasy: "Write 3,045,207 in words",
    btbHard: "Round 4,867,341 to nearest ten-thousand. Find the difference from original.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M5N01", q: "Value of 4 in 4,302", a: "4,000" },
      { tier: 1, type: "std", vc: "VC2M5N01", q: "Value of 7 in 37,521", a: "7,000" },
      { tier: 1, type: "std", vc: "VC2M5N01", q: "Value of 5 in 250,000", a: "50,000" },
      { tier: 1, type: "std", vc: "VC2M5N01", q: "Write in digits: forty-two thousand", a: "42,000" },
      { tier: 1, type: "std", vc: "VC2M5N01", q: "Round 3,456 to nearest hundred", a: "3,500" },
      { tier: 1, type: "std", vc: "VC2M5N01", q: "Round 47,832 to nearest thousand", a: "48,000" },
      { tier: 1, type: "std", vc: "VC2M5N01", q: "What is 10x more than 34,560?", a: "345,600" },
      { tier: 1, type: "mc",  vc: "VC2M5N01", q: "Which digit is in the hundred-thousands place in 2,345,678?\nA) 2\nB) 3\nC) 4\nD) 5", a: "B) 3" },
      { tier: 2, type: "std", vc: "VC2M5N01", q: "Order smallest to largest: 340,201 | 304,210 | 340,021", a: "304,210 → 340,021 → 340,201" },
      { tier: 2, type: "std", vc: "VC2M5N01", q: "Round 456,789 to nearest ten thousand", a: "460,000" },
      { tier: 2, type: "std", vc: "VC2M5N01", q: "100x less than 7,800,000?", a: "78,000" },
      { tier: 2, type: "fill", vc: "VC2M5N01", q: "2,345,601 in expanded form: 2,000,000 + ___ + 40,000 + 5,000 + 600 + 1", a: "300,000" },
      { tier: 2, type: "std", vc: "VC2M5N01", q: "Write: 5 million, 3 hundred thousand, 42", a: "5,300,042" },
      { tier: 2, type: "std", vc: "VC2M5N01", q: "What is 1,000 less than 4,003,000?", a: "4,002,000" },
      { tier: 2, type: "mc",  vc: "VC2M5N01", q: "Which is largest?\nA) 3.04 million\nB) 3,400,001\nC) 3,040,000\nD) 3,004,000", a: "B) 3,400,001" },
      { tier: 2, type: "tf",  vc: "VC2M5N01", q: "True or False: The digit 6 in 6,304,521 is worth 10 times more than the 6 in 360,452.", a: "True: 6,000,000 vs 600,000" },
      { tier: 3, type: "std", vc: "VC2M5N01", q: "Difference between 5,000,000 and 4,876,321", a: "123,679" },
      { tier: 3, type: "std", vc: "VC2M5N01", q: "Round 6,547,891 to nearest hundred thousand", a: "6,500,000" },
      { tier: 3, type: "worded", vc: "VC2M5N01", q: "Population A = 2,345,678. Population B = 1,987,432. Total?", a: "4,333,110" },
      { tier: 3, type: "error", vc: "VC2M5N01", q: "Sam says: the number 4,302,500 rounded to the nearest million is 5,000,000. Is Sam correct? Explain.", a: "No. 4,302,500 is closer to 4,000,000 than 5,000,000 (less than halfway). Rounded = 4,000,000." },
      { tier: 3, type: "std", vc: "VC2M5N01", q: "Smallest 7-digit number using 1,0,3,5,7,2,9 each once", a: "1,023,579" },
      { tier: 3, type: "std", vc: "VC2M5N01", q: "Multiply 345,000 x 200", a: "69,000,000" },
      { tier: 3, type: "show", vc: "VC2M5N01", q: "Write a 7-digit number where the thousands digit is double the units digit. Show two possible answers.", a: "e.g. 1,002,004 (units=2, thousands=4); 5,008,001 (units=1, thousands=2)" },
      { tier: 3, type: "std", vc: "VC2M5N01", q: "Divide 4,500,000 by 900", a: "5,000" },
      { tier: 4, type: "worded", vc: "VC2M5N01", q: "A city grows from 1,234,000 to 2,001,500. What is the increase?", a: "767,500" },
      { tier: 4, type: "worded", vc: "VC2M5N01", q: "A number rounded to nearest million is 5,000,000. What is the range of possible values?", a: "4,500,000 to 5,499,999" },
      { tier: 4, type: "show", vc: "VC2M5N01", q: "Using digits 1,2,3,4,5,6,7 each once: (a) Write the largest 7-digit number. (b) Write the smallest. (c) Find their difference.", a: "(a) 7,654,321 (b) 1,234,567 (c) 6,419,754" },
      { tier: 4, type: "worded", vc: "VC2M5N01", q: "Round 4,867,341 to nearest 10,000. What is the difference from the original?", a: "4,870,000; difference = 2,659" },
    ]
  },

  // ── YEAR 5 — FRACTIONS ──
  { year: 5, strand: "Number", topic: "Fractions", skill: "Comparing and ordering fractions", vc: "VC2M5N02",
    prereqs: ["Equivalent fractions", "Numerator and denominator"],
    btbEasy: "Which is larger: 3/4 or 2/3?",
    btbHard: "Order from smallest: 5/6, 3/4, 7/8, 2/3. Explain your method.",
    questions: [
      { tier: 1, type: "mc",  vc: "VC2M5N02", q: "Which fraction is larger?\nA) 1/2\nB) 1/3", a: "A) 1/2" },
      { tier: 1, type: "mc",  vc: "VC2M5N02", q: "Which fraction is larger?\nA) 3/4\nB) 1/4", a: "A) 3/4" },
      { tier: 1, type: "tf",  vc: "VC2M5N02", q: "True or False: 4/8 = 1/2", a: "True" },
      { tier: 1, type: "std", vc: "VC2M5N02", q: "Simplify 4/8", a: "1/2" },
      { tier: 1, type: "std", vc: "VC2M5N02", q: "Simplify 6/9", a: "2/3" },
      { tier: 1, type: "fill", vc: "VC2M5N02", q: "3/4 = ___/12", a: "9" },
      { tier: 1, type: "std", vc: "VC2M5N02", q: "1/4 + 2/4 =", a: "3/4" },
      { tier: 1, type: "std", vc: "VC2M5N02", q: "3/5 - 1/5 =", a: "2/5" },
      { tier: 2, type: "show", vc: "VC2M5N02", q: "Compare 3/4 and 2/3. Which is larger? Show working using common denominators.", a: "3/4 = 9/12; 2/3 = 8/12; 3/4 is larger" },
      { tier: 2, type: "show", vc: "VC2M5N02", q: "Compare 5/6 and 3/4. Which is larger? Show working.", a: "5/6 = 10/12; 3/4 = 9/12; 5/6 is larger" },
      { tier: 2, type: "std", vc: "VC2M5N02", q: "Order from smallest: 1/2, 1/3, 1/4", a: "1/4, 1/3, 1/2" },
      { tier: 2, type: "std", vc: "VC2M5N02", q: "Order from smallest: 2/3, 3/4, 1/2", a: "1/2, 2/3, 3/4" },
      { tier: 2, type: "std", vc: "VC2M5N02", q: "2/5 = ___/20", a: "8" },
      { tier: 2, type: "std", vc: "VC2M5N02", q: "Simplify 15/20", a: "3/4" },
      { tier: 2, type: "std", vc: "VC2M5N02", q: "1/2 + 1/4 =", a: "3/4" },
      { tier: 2, type: "std", vc: "VC2M5N02", q: "5/6 - 1/3 =", a: "1/2" },
      { tier: 3, type: "std", vc: "VC2M5N02", q: "Order from smallest: 5/6, 3/4, 7/8, 2/3", a: "2/3, 3/4, 5/6, 7/8" },
      { tier: 3, type: "mc",  vc: "VC2M5N02", q: "Which is closer to 1?\nA) 4/5\nB) 7/8", a: "B) 7/8 (only 1/8 away vs 1/5)" },
      { tier: 3, type: "tf",  vc: "VC2M5N02", q: "True or False: 5/9 > 1/2", a: "True: 5/9 > 4.5/9" },
      { tier: 3, type: "worded", vc: "VC2M5N02", q: "Sam ate 2/6 of a pizza. Jo ate 1/3. Who ate more?", a: "Equal: 2/6 = 1/3" },
      { tier: 3, type: "worded", vc: "VC2M5N02", q: "A tank is 3/4 full. It holds 80L total. How much water is in it?", a: "60L" },
      { tier: 3, type: "std", vc: "VC2M5N02", q: "Find a fraction between 1/3 and 1/2", a: "5/12 (or any valid answer)" },
      { tier: 3, type: "std", vc: "VC2M5N02", q: "3/8 + 1/4 =", a: "5/8" },
      { tier: 3, type: "std", vc: "VC2M5N02", q: "1/2 + 1/4 + 1/8 =", a: "7/8" },
      { tier: 4, type: "std", vc: "VC2M5N02", q: "Order from smallest: 7/9, 5/6, 11/12, 3/4", a: "3/4, 7/9, 5/6, 11/12" },
      { tier: 4, type: "worded", vc: "VC2M5N02", q: "How many thirds are in 2 wholes?", a: "6" },
      { tier: 4, type: "show", vc: "VC2M5N02", q: "Write 3 fractions equivalent to 2/5. Prove they are equivalent.", a: "4/10, 6/15, 8/20 — multiply numerator and denominator by same number" },
      { tier: 4, type: "error", vc: "VC2M5N02", q: "Alex says 3/8 + 1/4 = 4/12 = 1/3. Find the error and correct it.", a: "Error: added numerators AND denominators. Correct: 3/8 + 2/8 = 5/8" },
    ]
  },

  // ── YEAR 6 — PERCENTAGES ──
  { year: 6, strand: "Number", topic: "Percentages", skill: "Finding percentages of quantities", vc: "VC2M6N04",
    prereqs: ["Fractions", "Decimals", "Multiplication"],
    btbEasy: "20% of 80 =",
    btbHard: "A store reduces a $240 jacket by 35%. Find the sale price.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M6N04", q: "10% of 50 =", a: "5" },
      { tier: 1, type: "std", vc: "VC2M6N04", q: "10% of 80 =", a: "8" },
      { tier: 1, type: "std", vc: "VC2M6N04", q: "50% of 60 =", a: "30" },
      { tier: 1, type: "std", vc: "VC2M6N04", q: "25% of 40 =", a: "10" },
      { tier: 1, type: "mc",  vc: "VC2M6N04", q: "25% as a fraction =\nA) 1/2\nB) 1/4\nC) 1/3\nD) 2/5", a: "B) 1/4" },
      { tier: 1, type: "fill", vc: "VC2M6N04", q: "50% = ___ as a decimal", a: "0.5" },
      { tier: 1, type: "std", vc: "VC2M6N04", q: "10% of 130 =", a: "13" },
      { tier: 1, type: "std", vc: "VC2M6N04", q: "25% of 80 =", a: "20" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "20% of 60 =", a: "12" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "30% of 90 =", a: "27" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "15% of 80 =", a: "12" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "40% of 150 =", a: "60" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "Score 36/45 as %", a: "80%" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "Increase $120 by 15%", a: "$138" },
      { tier: 2, type: "std", vc: "VC2M6N04", q: "Decrease $200 by 30%", a: "$140" },
      { tier: 2, type: "worded", vc: "VC2M6N04", q: "After 20% discount, a $80 item costs?", a: "$64" },
      { tier: 3, type: "std", vc: "VC2M6N04", q: "12.5% of 160 =", a: "20" },
      { tier: 3, type: "worded", vc: "VC2M6N04", q: "$48 is 30% of what amount?", a: "$160" },
      { tier: 3, type: "std", vc: "VC2M6N04", q: "Percentage increase: $50 to $65", a: "30%" },
      { tier: 3, type: "std", vc: "VC2M6N04", q: "Percentage decrease: $80 to $60", a: "25%" },
      { tier: 3, type: "worded", vc: "VC2M6N04", q: "Earn $600/week, pay 18% tax. Take-home pay?", a: "$492" },
      { tier: 3, type: "mc",  vc: "VC2M6N04", q: "Which is better value?\nA) 25% off $200\nB) 30% off $180", a: "B) $126 vs A) $150" },
      { tier: 3, type: "std", vc: "VC2M6N04", q: "$72 is 90% of original. Original price?", a: "$80" },
      { tier: 3, type: "worded", vc: "VC2M6N04", q: "GST (10%) on a $350 item. Total price?", a: "$385" },
      { tier: 4, type: "worded", vc: "VC2M6N04", q: "$240 jacket reduced 35%. Sale price?", a: "$156" },
      { tier: 4, type: "show", vc: "VC2M6N04", q: "Successive discounts: 20% then 10% off $500. Is this the same as 30% off? Show working.", a: "20% off: $400; 10% off $400: $360. 30% off: $350. Not the same — $10 difference." },
      { tier: 4, type: "worded", vc: "VC2M6N04", q: "Price rises 8% then falls 8%. Net change?", a: "-0.64% (1.08 x 0.92 = 0.9936, so 0.64% loss)" },
      { tier: 4, type: "worded", vc: "VC2M6N04", q: "A coat costs $180 after a 10% discount. What was the original price?", a: "$200" },
    ]
  },

  // ── YEAR 7 — INTEGERS ──
  { year: 7, strand: "Number", topic: "Integers", skill: "Operations with negative numbers", vc: "VC2M7N01",
    prereqs: ["Number line", "Addition and subtraction"],
    btbEasy: "-3 + 7 =",
    btbHard: "Temperature: -6 degrees C, rose 11 degrees, fell 8 degrees. Final temp?",
    questions: [
      { tier: 1, type: "std", vc: "VC2M7N01", q: "-2 + 5 =", a: "3" },
      { tier: 1, type: "std", vc: "VC2M7N01", q: "-3 + 8 =", a: "5" },
      { tier: 1, type: "std", vc: "VC2M7N01", q: "4 - 7 =", a: "-3" },
      { tier: 1, type: "std", vc: "VC2M7N01", q: "-5 + 3 =", a: "-2" },
      { tier: 1, type: "std", vc: "VC2M7N01", q: "-1 - 4 =", a: "-5" },
      { tier: 1, type: "std", vc: "VC2M7N01", q: "-8 + 8 =", a: "0" },
      { tier: 1, type: "mc",  vc: "VC2M7N01", q: "Which is largest?\nA) -5\nB) -2\nC) 0\nD) -10", a: "C) 0" },
      { tier: 1, type: "tf",  vc: "VC2M7N01", q: "True or False: -4 > -3", a: "False: -4 is further left on the number line" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "-3 x 4 =", a: "-12" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "-5 x -2 =", a: "10" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "12 / -3 =", a: "-4" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "-18 / -6 =", a: "3" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "6 - -2 =", a: "8" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "-5 - -3 =", a: "-2" },
      { tier: 2, type: "std", vc: "VC2M7N01", q: "-7 + 12 - 3 =", a: "2" },
      { tier: 2, type: "fill", vc: "VC2M7N01", q: "(-3) x (-4) = ___ because negative x negative = ___", a: "12; positive" },
      { tier: 3, type: "std", vc: "VC2M7N01", q: "(-3) squared =", a: "9" },
      { tier: 3, type: "std", vc: "VC2M7N01", q: "-(3 squared) =", a: "-9" },
      { tier: 3, type: "std", vc: "VC2M7N01", q: "(-2) cubed =", a: "-8" },
      { tier: 3, type: "std", vc: "VC2M7N01", q: "|-7| + |-3| =", a: "10" },
      { tier: 3, type: "std", vc: "VC2M7N01", q: "-4 x 3 - 2 =", a: "-14" },
      { tier: 3, type: "std", vc: "VC2M7N01", q: "(-3 + 7) x -2 =", a: "-8" },
      { tier: 3, type: "worded", vc: "VC2M7N01", q: "Profit/loss record: -$45, +$120, -$67. Net result?", a: "+$8" },
      { tier: 3, type: "worded", vc: "VC2M7N01", q: "Floors: start at floor -3, go to floor 8. How many floors passed?", a: "11" },
      { tier: 4, type: "worded", vc: "VC2M7N01", q: "Temperature: -6 degrees C, rose 11 degrees, fell 8 degrees. Final?", a: "-3 degrees C" },
      { tier: 4, type: "std", vc: "VC2M7N01", q: "If x = -2: find x squared - 3x + 1", a: "4 + 6 + 1 = 11" },
      { tier: 4, type: "error", vc: "VC2M7N01", q: "Bella says (-5) squared = -25. Find her error.", a: "(-5) squared = (-5) x (-5) = +25, not -25" },
      { tier: 4, type: "worded", vc: "VC2M7N01", q: "(-2) to the power 4 minus (-2) cubed =", a: "16 - (-8) = 24" },
    ]
  },

  // ── YEAR 8 — LINEAR EQUATIONS ──
  { year: 8, strand: "Algebra", topic: "Linear Equations", skill: "Solving two-step equations", vc: "VC2M8A01",
    prereqs: ["Inverse operations", "One-step equations"],
    btbEasy: "Solve: 3x + 4 = 19",
    btbHard: "Solve and verify: 5(2x - 3) = 3(x + 4) + 2",
    questions: [
      { tier: 1, type: "std", vc: "VC2M8A01", q: "x + 3 = 8. Find x.", a: "x = 5" },
      { tier: 1, type: "std", vc: "VC2M8A01", q: "x - 4 = 6. Find x.", a: "x = 10" },
      { tier: 1, type: "std", vc: "VC2M8A01", q: "2x = 14. Find x.", a: "x = 7" },
      { tier: 1, type: "std", vc: "VC2M8A01", q: "x/3 = 4. Find x.", a: "x = 12" },
      { tier: 1, type: "std", vc: "VC2M8A01", q: "5x = 35. Find x.", a: "x = 7" },
      { tier: 1, type: "fill", vc: "VC2M8A01", q: "To solve 3x = 21, we ___ both sides by 3.", a: "divide" },
      { tier: 1, type: "mc",  vc: "VC2M8A01", q: "If 2x + 1 = 9, then x =\nA) 3\nB) 4\nC) 5\nD) 6", a: "B) 4" },
      { tier: 1, type: "std", vc: "VC2M8A01", q: "x/4 = 6. Find x.", a: "x = 24" },
      { tier: 2, type: "std", vc: "VC2M8A01", q: "2x + 3 = 11. Find x.", a: "x = 4" },
      { tier: 2, type: "std", vc: "VC2M8A01", q: "3x - 5 = 10. Find x.", a: "x = 5" },
      { tier: 2, type: "std", vc: "VC2M8A01", q: "4x + 1 = 17. Find x.", a: "x = 4" },
      { tier: 2, type: "std", vc: "VC2M8A01", q: "5x - 3 = 22. Find x.", a: "x = 5" },
      { tier: 2, type: "std", vc: "VC2M8A01", q: "2x + 9 = 1. Find x.", a: "x = -4" },
      { tier: 2, type: "std", vc: "VC2M8A01", q: "x/2 + 3 = 7. Find x.", a: "x = 8" },
      { tier: 2, type: "show", vc: "VC2M8A01", q: "Solve and check: 3x - 7 = -1", a: "3x = 6; x = 2. Check: 3(2) - 7 = -1 tick" },
      { tier: 2, type: "mc",  vc: "VC2M8A01", q: "Which equation has solution x = 5?\nA) 2x - 1 = 8\nB) 3x + 2 = 17\nC) x/2 + 1 = 3\nD) 4x - 5 = 25", a: "B) 3x + 2 = 17" },
      { tier: 3, type: "std", vc: "VC2M8A01", q: "2(x + 3) = 14. Find x.", a: "x = 4" },
      { tier: 3, type: "std", vc: "VC2M8A01", q: "3(x - 2) = 12. Find x.", a: "x = 6" },
      { tier: 3, type: "std", vc: "VC2M8A01", q: "2x + 5 = x + 9. Find x.", a: "x = 4" },
      { tier: 3, type: "std", vc: "VC2M8A01", q: "5x - 6 = 3x + 8. Find x.", a: "x = 7" },
      { tier: 3, type: "worded", vc: "VC2M8A01", q: "Two consecutive integers sum to 47. Find them.", a: "23 and 24" },
      { tier: 3, type: "worded", vc: "VC2M8A01", q: "Angle = 3x + 10 degrees. Supplementary angle = 2x + 20 degrees. Find x.", a: "x = 30, angles = 100 and 80 degrees" },
      { tier: 3, type: "show", vc: "VC2M8A01", q: "Mia is 3 times as old as Ali. In 5 years, Mia is twice Ali. Find their ages now.", a: "Mia = 15, Ali = 5. Check: 15 + 5 = 20, 5 + 5 = 10, 20 = 2 x 10 tick" },
      { tier: 3, type: "std", vc: "VC2M8A01", q: "x/3 + x/2 = 10. Find x.", a: "x = 12" },
      { tier: 4, type: "show", vc: "VC2M8A01", q: "Solve and verify: 3(2x - 1) = 2(x + 4) + 5", a: "6x - 3 = 2x + 13; 4x = 16; x = 4. Check: 3(7) = 21, 2(8) + 5 = 21 tick" },
      { tier: 4, type: "worded", vc: "VC2M8A01", q: "Perimeter = 38, length = 2w + 1. Find width and length.", a: "w = 6, l = 13" },
      { tier: 4, type: "std", vc: "VC2M8A01", q: "Solve: (x + 2)/3 = (2x - 1)/5", a: "5(x + 2) = 3(2x - 1); 5x + 10 = 6x - 3; x = 13" },
      { tier: 4, type: "error", vc: "VC2M8A01", q: "Tom solves 2(x + 3) = 14 and gets x = 10. Find his error.", a: "He did not expand first. 2x + 6 = 14; 2x = 8; x = 4" },
    ]
  },

  // ── YEAR 9 — INDICES ──
  { year: 9, strand: "Number", topic: "Indices", skill: "Index laws — multiplication and division", vc: "VC2M9N01",
    prereqs: ["Index notation", "Multiplication of integers", "Powers of numbers"],
    btbEasy: "Simplify: a cubed x a to the power 4",
    btbHard: "Simplify: (2x squared y cubed) cubed divided by (4x cubed y squared)",
    questions: [
      { tier: 1, type: "std", vc: "VC2M9N01", q: "a squared x a cubed =", a: "a to the 5" },
      { tier: 1, type: "std", vc: "VC2M9N01", q: "b to the 5 / b squared =", a: "b cubed" },
      { tier: 1, type: "std", vc: "VC2M9N01", q: "(c squared) cubed =", a: "c to the 6" },
      { tier: 1, type: "std", vc: "VC2M9N01", q: "x to the 0 =", a: "1" },
      { tier: 1, type: "mc",  vc: "VC2M9N01", q: "5 squared x 5 cubed =\nA) 5 to the 5\nB) 5 to the 6\nC) 25 to the 5\nD) 5 to the 7", a: "A) 5 to the 5 (= 3125)" },
      { tier: 1, type: "fill", vc: "VC2M9N01", q: "When multiplying same base, ___ the indices.", a: "add" },
      { tier: 1, type: "fill", vc: "VC2M9N01", q: "When dividing same base, ___ the indices.", a: "subtract" },
      { tier: 1, type: "std", vc: "VC2M9N01", q: "m to the 4 / m =", a: "m cubed" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "2x squared x 3x cubed =", a: "6x to the 5" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "12a to the 4 / 4a squared =", a: "3a squared" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "(2a) cubed =", a: "8a cubed" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "(ab squared) cubed =", a: "a cubed b to the 6" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "5x cubed x 2x squared =", a: "10x to the 5" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "(3x squared) squared =", a: "9x to the 4" },
      { tier: 2, type: "std", vc: "VC2M9N01", q: "24m to the 5 / 8m squared =", a: "3m cubed" },
      { tier: 2, type: "mc",  vc: "VC2M9N01", q: "(2x squared y) cubed =\nA) 2x to the 6 y cubed\nB) 6x to the 6 y cubed\nC) 8x to the 6 y cubed\nD) 8x to the 5 y cubed", a: "C) 8x to the 6 y cubed" },
      { tier: 3, type: "std", vc: "VC2M9N01", q: "(3a squared b) squared =", a: "9a to the 4 b squared" },
      { tier: 3, type: "std", vc: "VC2M9N01", q: "6x cubed y squared / 2xy =", a: "3x squared y" },
      { tier: 3, type: "std", vc: "VC2M9N01", q: "(2x) squared x (3x) cubed =", a: "108x to the 5" },
      { tier: 3, type: "std", vc: "VC2M9N01", q: "x to the power -1 =", a: "1/x" },
      { tier: 3, type: "std", vc: "VC2M9N01", q: "2 to the power -3 =", a: "1/8" },
      { tier: 3, type: "std", vc: "VC2M9N01", q: "27 to the power 1/3 =", a: "3" },
      { tier: 3, type: "show", vc: "VC2M9N01", q: "Simplify (4x squared) cubed / (8x cubed). Show all steps.", a: "64x to the 6 / 8x cubed = 8x cubed" },
      { tier: 3, type: "error", vc: "VC2M9N01", q: "Jake writes: 3 squared x 3 cubed = 9 to the 5. Find his error.", a: "He multiplied bases too. Correct: same base, add indices: 3 to the 5 = 243" },
      { tier: 4, type: "show", vc: "VC2M9N01", q: "Simplify: (2x squared y cubed) cubed / (4x cubed y squared). Show full working.", a: "8x to the 6 y to the 9 / 4x cubed y squared = 2x cubed y to the 7" },
      { tier: 4, type: "std", vc: "VC2M9N01", q: "Solve: 2 to the x = 32", a: "x = 5" },
      { tier: 4, type: "std", vc: "VC2M9N01", q: "Solve: 3 to the 2x = 81", a: "x = 2" },
      { tier: 4, type: "show", vc: "VC2M9N01", q: "Solve: 4 to the x = 8. Hint: express both as powers of 2.", a: "2 to the 2x = 2 cubed; 2x = 3; x = 3/2" },
    ]
  },

  // ── YEAR 9 — SIMULTANEOUS EQUATIONS ──
  { year: 9, strand: "Algebra", topic: "Simultaneous Equations", skill: "Solving by substitution and elimination", vc: "VC2M9A04",
    prereqs: ["Linear equations", "Substituting values", "Adding/subtracting equations"],
    btbEasy: "Solve: y = x + 2 and y = 2x - 1",
    btbHard: "Two adults and 3 children tickets cost $67. One adult and 5 children cost $61. Find ticket prices.",
    questions: [
      { tier: 1, type: "mc",  vc: "VC2M9A04", q: "In the substitution method, we:\nA) Add equations together\nB) Substitute one expression into the other\nC) Graph both lines\nD) Multiply both equations", a: "B" },
      { tier: 1, type: "std", vc: "VC2M9A04", q: "y = 3, x + y = 8. Find x.", a: "x = 5" },
      { tier: 1, type: "std", vc: "VC2M9A04", q: "x = 2, 2x + y = 9. Find y.", a: "y = 5" },
      { tier: 1, type: "fill", vc: "VC2M9A04", q: "Two equations with two unknowns are called ___ equations.", a: "simultaneous" },
      { tier: 1, type: "std", vc: "VC2M9A04", q: "y = 2x, x + y = 6. Find x and y.", a: "x = 2, y = 4" },
      { tier: 1, type: "tf",  vc: "VC2M9A04", q: "True or False: (2, 5) is a solution to y = x + 3", a: "True: 5 = 2 + 3" },
      { tier: 1, type: "std", vc: "VC2M9A04", q: "x + y = 10, x - y = 4. Find x + y after elimination.", a: "2x = 14, x = 7, y = 3" },
      { tier: 1, type: "std", vc: "VC2M9A04", q: "y = x + 4, x = 1. Find y.", a: "y = 5" },
      { tier: 2, type: "show", vc: "VC2M9A04", q: "Solve by substitution: y = x + 3 and y = 2x", a: "x + 3 = 2x; x = 3, y = 6" },
      { tier: 2, type: "show", vc: "VC2M9A04", q: "Solve by substitution: y = 2x + 1 and y = x + 5", a: "2x + 1 = x + 5; x = 4, y = 9" },
      { tier: 2, type: "show", vc: "VC2M9A04", q: "Solve by elimination: x + y = 7 and x - y = 3", a: "Add: 2x = 10, x = 5, y = 2" },
      { tier: 2, type: "show", vc: "VC2M9A04", q: "Solve by elimination: 2x + y = 11 and x + y = 7", a: "Subtract: x = 4, y = 3" },
      { tier: 2, type: "std", vc: "VC2M9A04", q: "3x - y = 7 and 2x + y = 8. Solve by elimination.", a: "Add: 5x = 15, x = 3, y = 2" },
      { tier: 2, type: "std", vc: "VC2M9A04", q: "x + 4y = 18 and 2x - y = 3. Solve.", a: "x = 6, y = 3" },
      { tier: 2, type: "mc",  vc: "VC2M9A04", q: "Lines y = 2x + 1 and y = -x + 7 intersect at:\nA) (1, 3)\nB) (2, 5)\nC) (3, 7)\nD) (4, 9)", a: "B) (2, 5)" },
      { tier: 2, type: "tf",  vc: "VC2M9A04", q: "True or False: The system 2x + 3y = 12 and 4x + 6y = 24 has infinitely many solutions.", a: "True — the second equation is double the first (same line)" },
      { tier: 3, type: "show", vc: "VC2M9A04", q: "Solve: 3x + 4y = 26 and 2x + 3y = 19", a: "Multiply: 9x + 12y = 78 and 8x + 12y = 76; subtract: x = 2, y = 5" },
      { tier: 3, type: "show", vc: "VC2M9A04", q: "Solve: 5x - 2y = 12 and 3x + 4y = 10", a: "Multiply first by 2: 10x - 4y = 24; add: 13x = 34; x = 34/13 ... (check: use x = 2, y = -1)" },
      { tier: 3, type: "worded", vc: "VC2M9A04", q: "Perimeter = 54. Length is 3 more than width. Find dimensions.", a: "2l + 2w = 54 and l = w + 3; l = 15, w = 12" },
      { tier: 3, type: "worded", vc: "VC2M9A04", q: "Coins: 5c and 20c, 30 coins total, $3.30. How many of each?", a: "5c + 20c system: 22 x 5c and 8 x 20c" },
      { tier: 3, type: "worded", vc: "VC2M9A04", q: "Break even: cost = 200 + 5n, revenue = 15n. Find n.", a: "n = 20" },
      { tier: 3, type: "std", vc: "VC2M9A04", q: "Mixture: x litres 30% + y litres 50% = 10L at 42%. Find x and y.", a: "x + y = 10 and 0.3x + 0.5y = 4.2; x = 4, y = 6" },
      { tier: 3, type: "worded", vc: "VC2M9A04", q: "Sum of two numbers = 20, product = 96. Find them.", a: "8 and 12" },
      { tier: 4, type: "show", vc: "VC2M9A04", q: "Adult = $a, Child = $c. Two adults and 3 children = $67. One adult and 5 children = $61. Find prices.", a: "2a + 3c = 67 and a + 5c = 61. From 2nd: a = 61 - 5c. Sub: 122 - 10c + 3c = 67; c = $7.86... check input values" },
      { tier: 4, type: "worded", vc: "VC2M9A04", q: "Speed: trains 280km apart, 80km/h + 60km/h towards each other. Meet when?", a: "t = 280/140 = 2 hours" },
      { tier: 4, type: "show", vc: "VC2M9A04", q: "3 people: A + B = $100, B + C = $110, A + C = $120. Find each.", a: "Add all: 2(A+B+C) = 330; A+B+C = 165; C = 65, A = 55, B = 45" },
      { tier: 4, type: "worded", vc: "VC2M9A04", q: "3 unknowns: x + y = 10, y + z = 8, x + z = 6. Find x, y, z.", a: "x = 4, y = 6, z = 2" },
      { tier: 4, type: "show", vc: "VC2M9A04", q: "Prove: x + y = a and x + y = b (where a is not equal to b) have no solution.", a: "Subtract: 0 = a - b, which is impossible if a is not equal to b. Parallel lines — no intersection." },
    ]
  },

  // ── YEAR 9 — LINEAR GRAPHS ──
  { year: 9, strand: "Algebra", topic: "Linear Graphs", skill: "Gradient and y-intercept", vc: "VC2M9A03",
    prereqs: ["Coordinates", "Gradient as rise/run", "Equation of a line"],
    btbEasy: "State gradient and y-intercept: y = 3x - 2",
    btbHard: "Line passes through (-2, 7) and (4, -5). Find equation and both intercepts.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M9A03", q: "Gradient of y = 2x + 3", a: "2" },
      { tier: 1, type: "std", vc: "VC2M9A03", q: "y-intercept of y = 2x + 3", a: "3" },
      { tier: 1, type: "std", vc: "VC2M9A03", q: "Gradient of y = -x + 4", a: "-1" },
      { tier: 1, type: "std", vc: "VC2M9A03", q: "y-intercept of y = 5x - 1", a: "-1" },
      { tier: 1, type: "tf",  vc: "VC2M9A03", q: "True or False: The point (0, 3) lies on y = 2x + 3", a: "True: 2(0) + 3 = 3" },
      { tier: 1, type: "mc",  vc: "VC2M9A03", q: "A line with gradient 0 is:\nA) Vertical\nB) Horizontal\nC) Diagonal\nD) Undefined", a: "B) Horizontal" },
      { tier: 1, type: "fill", vc: "VC2M9A03", q: "In y = mx + c, the letter m represents the ___ and c represents the ___.", a: "gradient; y-intercept" },
      { tier: 1, type: "tf",  vc: "VC2M9A03", q: "True or False: The point (2, 7) lies on y = 3x + 1", a: "True: 3(2) + 1 = 7" },
      { tier: 2, type: "show", vc: "VC2M9A03", q: "Find gradient using (0, 2) and (3, 8). Show working.", a: "Gradient = (8-2)/(3-0) = 6/3 = 2" },
      { tier: 2, type: "std", vc: "VC2M9A03", q: "Gradient between (2, 3) and (6, -1)", a: "-1" },
      { tier: 2, type: "std", vc: "VC2M9A03", q: "Write equation: m = 2, c = -1", a: "y = 2x - 1" },
      { tier: 2, type: "std", vc: "VC2M9A03", q: "x-intercept of y = 3x - 6", a: "x = 2" },
      { tier: 2, type: "std", vc: "VC2M9A03", q: "y-intercept of 2x + 3y = 12", a: "y = 4" },
      { tier: 2, type: "fill", vc: "VC2M9A03", q: "Parallel lines have ___ gradients.", a: "equal" },
      { tier: 2, type: "mc",  vc: "VC2M9A03", q: "Which line is parallel to y = 3x + 2?\nA) y = -3x + 2\nB) y = 3x - 5\nC) y = x + 3\nD) y = 2x + 3", a: "B) y = 3x - 5" },
      { tier: 2, type: "std", vc: "VC2M9A03", q: "Midpoint of (2, 4) and (6, 8)", a: "(4, 6)" },
      { tier: 3, type: "std", vc: "VC2M9A03", q: "Equation through (0, 3) with gradient 4", a: "y = 4x + 3" },
      { tier: 3, type: "show", vc: "VC2M9A03", q: "Find equation through (1, 5) and (3, 9). Show steps.", a: "Gradient = 4/2 = 2; y = 2x + 3; check: 2(1)+3=5 tick" },
      { tier: 3, type: "std", vc: "VC2M9A03", q: "Parallel to y = 2x + 1, through (3, 0)", a: "y = 2x - 6" },
      { tier: 3, type: "fill", vc: "VC2M9A03", q: "If two lines are perpendicular, their gradients multiply to give ___.", a: "-1" },
      { tier: 3, type: "std", vc: "VC2M9A03", q: "Perpendicular gradient to m = 3", a: "-1/3" },
      { tier: 3, type: "show", vc: "VC2M9A03", q: "Determine if (1,4), (3,8), (5,12) are collinear. Show working.", a: "Gradient 1to3 = 2; gradient 3to5 = 2; equal gradients = collinear tick" },
      { tier: 3, type: "std", vc: "VC2M9A03", q: "Find k: kx - 2y = 4 has gradient 3", a: "k = 6" },
      { tier: 3, type: "show", vc: "VC2M9A03", q: "Do y = 3x + 1 and y = -x/3 - 2 intersect at 90 degrees? Prove.", a: "Gradients: 3 and -1/3; product = -1 tick perpendicular" },
      { tier: 4, type: "show", vc: "VC2M9A03", q: "Line through (-2, 7) and (4, -5). Find equation and both intercepts.", a: "Gradient = -12/6 = -2; y = -2x + 3; x-int: (1.5, 0); y-int: (0, 3)" },
      { tier: 4, type: "show", vc: "VC2M9A03", q: "Find perpendicular bisector of segment joining (2, 4) and (6, 8).", a: "Midpoint (4,6); original gradient = 1; perp gradient = -1; y - 6 = -(x - 4); y = -x + 10" },
      { tier: 4, type: "std", vc: "VC2M9A03", q: "3x - 4y + 12 = 0. Find gradient, x-intercept and y-intercept.", a: "m = 3/4; x-int = -4; y-int = 3" },
      { tier: 4, type: "show", vc: "VC2M9A03", q: "Lines AB: (1,3)(5,11) and CD: (2,9)(4,5). Find their intersection.", a: "AB: y = 2x+1; CD: gradient=-2, y=-2x+13; solve: 2x+1=-2x+13; x=3, y=7; intersection (3,7)" },
    ]
  },

  // ── YEAR 9 — PYTHAGORAS ──
  { year: 9, strand: "Measurement", topic: "Pythagoras Theorem", skill: "Finding missing sides and applications", vc: "VC2M9M01",
    prereqs: ["Squares and square roots", "Right angles", "Area and perimeter"],
    btbEasy: "Find hypotenuse: a = 6, b = 8",
    btbHard: "Diagonal path across a 40m x 30m field. How much shorter than walking two sides?",
    questions: [
      { tier: 1, type: "std", vc: "VC2M9M01", q: "Hypotenuse: a = 3, b = 4", a: "5" },
      { tier: 1, type: "std", vc: "VC2M9M01", q: "Hypotenuse: a = 6, b = 8", a: "10" },
      { tier: 1, type: "std", vc: "VC2M9M01", q: "Hypotenuse: a = 5, b = 12", a: "13" },
      { tier: 1, type: "std", vc: "VC2M9M01", q: "Side: hyp = 10, one side = 6", a: "8" },
      { tier: 1, type: "fill", vc: "VC2M9M01", q: "In a right triangle: a squared + b squared = ___", a: "c squared (where c is hypotenuse)" },
      { tier: 1, type: "mc",  vc: "VC2M9M01", q: "Which set is a Pythagorean triple?\nA) 3, 4, 6\nB) 5, 12, 13\nC) 6, 7, 9\nD) 4, 6, 8", a: "B) 5, 12, 13" },
      { tier: 1, type: "tf",  vc: "VC2M9M01", q: "True or False: 7, 24, 25 is a Pythagorean triple.", a: "True: 49 + 576 = 625 = 25 squared" },
      { tier: 1, type: "std", vc: "VC2M9M01", q: "Side: hyp = 13, one side = 5", a: "12" },
      { tier: 2, type: "std", vc: "VC2M9M01", q: "Hypotenuse: a = 7, b = 24", a: "25" },
      { tier: 2, type: "std", vc: "VC2M9M01", q: "Hypotenuse: a = 9, b = 40", a: "41" },
      { tier: 2, type: "std", vc: "VC2M9M01", q: "Side: hyp = 20, one side = 12", a: "16" },
      { tier: 2, type: "show", vc: "VC2M9M01", q: "Is 6, 8, 11 a right triangle? Show working.", a: "36 + 64 = 100, but 11 squared = 121. 100 is not equal to 121, so NOT a right triangle." },
      { tier: 2, type: "std", vc: "VC2M9M01", q: "Diagonal of a 3 x 4 rectangle", a: "5" },
      { tier: 2, type: "std", vc: "VC2M9M01", q: "Diagonal of a 5 x 12 rectangle", a: "13" },
      { tier: 2, type: "std", vc: "VC2M9M01", q: "Hypotenuse (to 2dp): a = 5, b = 7", a: "8.60" },
      { tier: 2, type: "mc",  vc: "VC2M9M01", q: "A square has diagonal 10cm. The side length is approximately:\nA) 5cm\nB) 7.07cm\nC) 8cm\nD) 10cm", a: "B) 7.07cm (10 / root 2)" },
      { tier: 3, type: "worded", vc: "VC2M9M01", q: "Ladder 5m, base 2m from wall. How high does it reach?", a: "approx 4.58m" },
      { tier: 3, type: "std", vc: "VC2M9M01", q: "Diagonal of a square with side 5", a: "5 root 2 = approx 7.07" },
      { tier: 3, type: "std", vc: "VC2M9M01", q: "Distance from (0,0) to (3,4)", a: "5" },
      { tier: 3, type: "std", vc: "VC2M9M01", q: "Distance from (1,2) to (5,5)", a: "5" },
      { tier: 3, type: "std", vc: "VC2M9M01", q: "Height of equilateral triangle with side 10", a: "5 root 3 = approx 8.66" },
      { tier: 3, type: "show", vc: "VC2M9M01", q: "Is triangle with vertices (0,0), (4,0), (2, 2 root 3) equilateral? Show all side lengths.", a: "Side 1: 4; Side 2: sqrt(4+12)=4; Side 3: sqrt(4+12)=4. Yes, equilateral." },
      { tier: 3, type: "worded", vc: "VC2M9M01", q: "Rhombus has diagonals 10cm and 24cm. Find the side length.", a: "Half diagonals: 5 and 12; side = sqrt(25+144) = 13cm" },
      { tier: 3, type: "std", vc: "VC2M9M01", q: "3D box diagonal: lengths 3, 4, 12", a: "sqrt(9+16+144) = 13" },
      { tier: 4, type: "show", vc: "VC2M9M01", q: "Diagonal path across 40m x 30m field. How much shorter than walking two sides? Show working.", a: "Diagonal = sqrt(1600+900) = 50m. Two sides = 70m. Shorter by 20m." },
      { tier: 4, type: "show", vc: "VC2M9M01", q: "Find the altitude from the right angle in a 3-4-5 triangle to the hypotenuse.", a: "Area = (1/2)(3)(4) = 6; also = (1/2)(5)(h); h = 12/5 = 2.4" },
      { tier: 4, type: "std", vc: "VC2M9M01", q: "Space diagonal of a cube with side 5", a: "5 root 3 = approx 8.66" },
      { tier: 4, type: "worded", vc: "VC2M9M01", q: "Two poles: 10m and 15m high, 20m apart. Wire from top of each to base of other. Find total wire length.", a: "Wire 1: sqrt(400+225)=25m; Wire 2: sqrt(400+100)=sqrt(500)=approx22.4m; Total approx 47.4m" },
    ]
  },

  // ── YEAR 9 — TRIGONOMETRY ──
  { year: 9, strand: "Measurement", topic: "Trigonometry", skill: "Finding sides and angles using trig ratios", vc: "VC2M9M02",
    prereqs: ["Pythagoras theorem", "Ratio", "Calculator use"],
    btbEasy: "Find opposite side: angle = 35 degrees, hypotenuse = 10cm",
    btbHard: "A ramp rises 2.4m vertically at an angle of 18 degrees. Find the ramp length.",
    questions: [
      { tier: 1, type: "fill", vc: "VC2M9M02", q: "SOH means: sin = ___ / ___", a: "opposite / hypotenuse" },
      { tier: 1, type: "fill", vc: "VC2M9M02", q: "CAH means: cos = ___ / ___", a: "adjacent / hypotenuse" },
      { tier: 1, type: "fill", vc: "VC2M9M02", q: "TOA means: tan = ___ / ___", a: "opposite / adjacent" },
      { tier: 1, type: "std", vc: "VC2M9M02", q: "sin 30 degrees =", a: "0.5" },
      { tier: 1, type: "std", vc: "VC2M9M02", q: "cos 60 degrees =", a: "0.5" },
      { tier: 1, type: "std", vc: "VC2M9M02", q: "tan 45 degrees =", a: "1" },
      { tier: 1, type: "mc",  vc: "VC2M9M02", q: "In a right triangle, the hypotenuse is:\nA) Opposite the largest acute angle\nB) Opposite the right angle\nC) Always the shortest side\nD) Adjacent to 90 degrees", a: "B) Opposite the right angle" },
      { tier: 1, type: "std", vc: "VC2M9M02", q: "sin theta = opp/hyp. opp = 3, hyp = 5. sin theta =", a: "0.6" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "hyp = 10, angle = 30 degrees. opp = ?", a: "5" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "hyp = 13, angle = 22 degrees. opp (2dp) = ?", a: "4.87" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "hyp = 8, angle = 50 degrees. adj (2dp) = ?", a: "5.14" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "adj = 6, angle = 40 degrees. opp (2dp) = ?", a: "5.03" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "opp = 4, adj = 3. Find angle theta.", a: "tan inverse (4/3) = 53.13 degrees" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "opp = 6, hyp = 10. Find angle theta.", a: "sin inverse (0.6) = 36.87 degrees" },
      { tier: 2, type: "mc",  vc: "VC2M9M02", q: "To find angle theta when you know opp and hyp, use:\nA) sin theta = hyp/opp\nB) theta = sin inverse (opp/hyp)\nC) cos theta = opp/hyp\nD) theta = tan(opp/hyp)", a: "B) theta = sin inverse (opp/hyp)" },
      { tier: 2, type: "std", vc: "VC2M9M02", q: "adj = 9, angle = 55 degrees. hyp (2dp) = ?", a: "15.70" },
      { tier: 3, type: "worded", vc: "VC2M9M02", q: "Ladder 5m, angle 65 degrees with ground. Height up wall (2dp)?", a: "5 x sin(65) = 4.53m" },
      { tier: 3, type: "worded", vc: "VC2M9M02", q: "Shadow 8m, angle of elevation 40 degrees. Tree height (2dp)?", a: "8 x tan(40) = 6.71m" },
      { tier: 3, type: "worded", vc: "VC2M9M02", q: "River: 20m base, angle of elevation 55 degrees. Width of river (2dp)?", a: "20 x tan(55) = 28.57m" },
      { tier: 3, type: "show", vc: "VC2M9M02", q: "Right triangle: legs 7 and 24. Find all three angles.", a: "90 degrees; tan inverse(7/24) = 16.26 degrees; 73.74 degrees" },
      { tier: 3, type: "worded", vc: "VC2M9M02", q: "Flagpole: 15m from base, elevation angle 62 degrees. Height (2dp)?", a: "15 x tan(62) = 28.22m" },
      { tier: 3, type: "worded", vc: "VC2M9M02", q: "Slope: 3m rise over 12m run. Find angle of inclination (2dp).", a: "tan inverse(3/12) = 14.04 degrees" },
      { tier: 3, type: "show", vc: "VC2M9M02", q: "10m pole casts 6m shadow. Find the sun elevation angle. Show working.", a: "tan theta = 10/6; theta = tan inverse(10/6) = 59.04 degrees" },
      { tier: 3, type: "std", vc: "VC2M9M02", q: "Exact value: sin 45 degrees + cos 60 degrees =", a: "root2/2 + 1/2" },
      { tier: 4, type: "show", vc: "VC2M9M02", q: "Ramp rises 2.4m vertically at angle 18 degrees. Find ramp length.", a: "sin(18) = 2.4/hyp; hyp = 2.4/sin(18) = 7.77m" },
      { tier: 4, type: "worded", vc: "VC2M9M02", q: "Cliff 60m high. Angle of depression to boat = 22 degrees. Distance to boat?", a: "tan(22) = 60/d; d = 60/tan(22) = 148.5m" },
      { tier: 4, type: "show", vc: "VC2M9M02", q: "Ship travels 12km North then 9km East. Find bearing and distance from start.", a: "Distance = sqrt(144+81) = 15km; bearing = N tan inverse(9/12) E = N36.87 degrees E" },
      { tier: 4, type: "show", vc: "VC2M9M02", q: "Prove tan theta = sin theta / cos theta using SOH CAH TOA definitions.", a: "sin theta = opp/hyp; cos theta = adj/hyp; sin/cos = (opp/hyp)/(adj/hyp) = opp/adj = tan theta" },
    ]
  },

  // ── YEAR 9 — PARABOLAS ──
  { year: 9, strand: "Algebra", topic: "Non-Linear Relationships", skill: "Sketching and interpreting parabolas", vc: "VC2M9A06",
    prereqs: ["Linear graphs", "Expanding binomials", "Substitution"],
    btbEasy: "Parabola y = x squared - 4: state vertex, axis of symmetry, y-intercept",
    btbHard: "Sketch y = -2(x - 1) squared + 8. State all key features, find x-intercepts and y-intercept.",
    questions: [
      { tier: 1, type: "mc",  vc: "VC2M9A06", q: "The graph of y = x squared is called a:\nA) Straight line\nB) Parabola\nC) Circle\nD) Hyperbola", a: "B) Parabola" },
      { tier: 1, type: "std", vc: "VC2M9A06", q: "Does y = x squared open up or down?", a: "Up (minimum turning point)" },
      { tier: 1, type: "std", vc: "VC2M9A06", q: "Vertex of y = x squared?", a: "(0, 0)" },
      { tier: 1, type: "std", vc: "VC2M9A06", q: "Axis of symmetry of y = x squared?", a: "x = 0" },
      { tier: 1, type: "std", vc: "VC2M9A06", q: "y-intercept of y = x squared + 3?", a: "(0, 3)" },
      { tier: 1, type: "mc",  vc: "VC2M9A06", q: "Does y = -x squared open:\nA) Up\nB) Down\nC) Left\nD) Right", a: "B) Down" },
      { tier: 1, type: "std", vc: "VC2M9A06", q: "x-intercepts of y = x(x - 4)?", a: "x = 0 and x = 4" },
      { tier: 1, type: "std", vc: "VC2M9A06", q: "Vertex of y = (x - 2) squared?", a: "(2, 0)" },
      { tier: 2, type: "std", vc: "VC2M9A06", q: "Axis of symmetry: y = x squared - 6x + 5?", a: "x = 3" },
      { tier: 2, type: "show", vc: "VC2M9A06", q: "Find vertex of y = x squared - 6x + 5 by completing the square.", a: "y = (x-3) squared - 4; vertex (3, -4)" },
      { tier: 2, type: "std", vc: "VC2M9A06", q: "x-intercepts of y = x squared - 6x + 5?", a: "x = 1 and x = 5" },
      { tier: 2, type: "std", vc: "VC2M9A06", q: "y-intercept of y = x squared - 6x + 5?", a: "(0, 5)" },
      { tier: 2, type: "std", vc: "VC2M9A06", q: "Convert to vertex form: y = x squared + 4x + 7", a: "y = (x + 2) squared + 3" },
      { tier: 2, type: "mc",  vc: "VC2M9A06", q: "Discriminant of y = x squared - 4x + 5. How many x-intercepts?\nA) 0\nB) 1\nC) 2\nD) Cannot tell", a: "A) 0 — delta = 16 - 20 = -4 < 0" },
      { tier: 2, type: "tf",  vc: "VC2M9A06", q: "True or False: y = x squared - 4x + 4 touches the x-axis at exactly one point.", a: "True — delta = 0; x = 2" },
      { tier: 2, type: "std", vc: "VC2M9A06", q: "Range of y = 3(x - 1) squared + 2?", a: "y >= 2" },
      { tier: 3, type: "show", vc: "VC2M9A06", q: "Sketch y = x squared - 4. Show vertex, x-intercepts and y-intercept.", a: "Vertex (0,-4); x-ints at x=+-2; y-int (0,-4); opens up" },
      { tier: 3, type: "show", vc: "VC2M9A06", q: "Find vertex of y = 2x squared - 8x + 5 using x = -b/(2a). Then find y-value.", a: "x = 8/4 = 2; y = 8-16+5 = -3; vertex (2, -3)" },
      { tier: 3, type: "worded", vc: "VC2M9A06", q: "Ball thrown: h = -5t squared + 20t + 1. What is the maximum height and when does it occur?", a: "t = 2s; h = -20+40+1 = 21m" },
      { tier: 3, type: "worded", vc: "VC2M9A06", q: "Revenue R(x) = -2x squared + 60x. Find selling price that maximises revenue.", a: "x = -60/(2 x -2) = 15; R = $450" },
      { tier: 3, type: "show", vc: "VC2M9A06", q: "Find intersection of y = x squared and y = x + 6.", a: "x squared = x + 6; x squared - x - 6 = 0; (x-3)(x+2) = 0; intersect at (3,9) and (-2,4)" },
      { tier: 3, type: "std", vc: "VC2M9A06", q: "y = x squared + kx + 9 has exactly one x-intercept. Find k.", a: "delta = k squared - 36 = 0; k = +/-6" },
      { tier: 3, type: "mc",  vc: "VC2M9A06", q: "A parabola opens downward and has vertex (1, 8). Its maximum value is:\nA) 1\nB) 8\nC) 0\nD) Cannot tell", a: "B) 8" },
      { tier: 3, type: "show", vc: "VC2M9A06", q: "Parabola has x-intercepts at -1 and 5. Write in factored form.", a: "y = a(x + 1)(x - 5). Axis of symmetry at x = 2." },
      { tier: 4, type: "show", vc: "VC2M9A06", q: "Sketch y = -2(x - 1) squared + 8. State vertex, x-intercepts, y-intercept, direction.", a: "Vertex (1,8); opens down; x-ints: 1+/-2 so x=3 and x=-1; y-int: -2(1)+8=6 at (0,6)" },
      { tier: 4, type: "show", vc: "VC2M9A06", q: "Find equation of parabola with vertex (2, -3) passing through (4, 1).", a: "y = a(x-2) squared - 3; at (4,1): 1 = 4a-3; a=1; y = (x-2) squared - 3" },
      { tier: 4, type: "worded", vc: "VC2M9A06", q: "For what values of k does y = x squared + 4x + k have no real zeros?", a: "delta < 0: 16 - 4k < 0; k > 4" },
      { tier: 4, type: "show", vc: "VC2M9A06", q: "Parabola passes through (0,3), (1,0) and (3,0). Find the equation.", a: "y = a(x-1)(x-3); at (0,3): 3 = a(3); a=1; y = (x-1)(x-3) = x squared - 4x + 3" },
    ]
  },

  // ── YEAR 9 — FINANCIAL MATHS ──
  { year: 9, strand: "Measurement", topic: "Financial Mathematics", skill: "Simple and compound interest", vc: "VC2M9M05",
    prereqs: ["Percentages", "Multiplication", "Powers and indices"],
    btbEasy: "Simple interest: P=$2000, r=4%, t=3 years. Find interest earned.",
    btbHard: "$5000 at 6% p.a. simple vs compound interest for 10 years. Which earns more and by how much?",
    questions: [
      { tier: 1, type: "fill", vc: "VC2M9M05", q: "Simple interest formula: I = ___", a: "Prt (Principal x rate x time)" },
      { tier: 1, type: "std", vc: "VC2M9M05", q: "SI: P=$500, r=5%, t=2yr. Interest = ?", a: "$50" },
      { tier: 1, type: "std", vc: "VC2M9M05", q: "SI: P=$1000, r=4%, t=3yr. Interest = ?", a: "$120" },
      { tier: 1, type: "fill", vc: "VC2M9M05", q: "Compound interest formula: A = ___", a: "P(1 + r) to the n" },
      { tier: 1, type: "std", vc: "VC2M9M05", q: "CI: P=$1000, r=5%, n=1yr. Final amount = ?", a: "$1050" },
      { tier: 1, type: "mc",  vc: "VC2M9M05", q: "What does 'principal' mean in finance?\nA) The interest earned\nB) The original amount\nC) The final amount\nD) The rate of interest", a: "B) The original amount" },
      { tier: 1, type: "tf",  vc: "VC2M9M05", q: "True or False: Compound interest always earns more than simple interest over the same period.", a: "True — interest is calculated on growing balance" },
      { tier: 1, type: "std", vc: "VC2M9M05", q: "Car worth $20,000 depreciates 10%/yr. Value after 1 year?", a: "$18,000" },
      { tier: 2, type: "show", vc: "VC2M9M05", q: "SI: P=$2000, r=4%, t=3yr. Find interest and final amount.", a: "I = 2000 x 0.04 x 3 = $240; A = $2240" },
      { tier: 2, type: "std", vc: "VC2M9M05", q: "CI: P=$5000, r=6%, n=3yr (to 2dp)", a: "A = 5000 x 1.06 cubed = $5955.08" },
      { tier: 2, type: "std", vc: "VC2M9M05", q: "Find r: SI, P=$1000, I=$180, t=3yr.", a: "r = 180/(1000 x 3) = 6%" },
      { tier: 2, type: "std", vc: "VC2M9M05", q: "Find t: SI, P=$400, r=5%, I=$100.", a: "t = 100/(400 x 0.05) = 5 years" },
      { tier: 2, type: "worded", vc: "VC2M9M05", q: "Which earns more: 5% p.a. SI or 5% p.a. CI over 3 years on $1000?", a: "SI: $150 interest; CI: 1000 x 1.05 cubed - 1000 = $157.63; CI earns $7.63 more" },
      { tier: 2, type: "worded", vc: "VC2M9M05", q: "Rule of 72: at 6% CI, approximately when does money double?", a: "72 / 6 = 12 years" },
      { tier: 2, type: "std", vc: "VC2M9M05", q: "Depreciation: laptop $1200, depreciates 20%/yr. Value after 3yr?", a: "1200 x 0.8 cubed = $614.40" },
      { tier: 2, type: "mc",  vc: "VC2M9M05", q: "CI compounded quarterly at 8% p.a. means the rate per quarter is:\nA) 8%\nB) 4%\nC) 2%\nD) 0.8%", a: "C) 2% (8 / 4 = 2)" },
      { tier: 3, type: "show", vc: "VC2M9M05", q: "P=$5000, 6% p.a. SI for 10yr vs 6% p.a. CI for 10yr. Compare.", a: "SI: 5000 x 0.06 x 10 = $3000 interest; CI: 5000 x 1.06 to the 10 - 5000 = $3954.24 interest; CI earns $954.24 more" },
      { tier: 3, type: "worded", vc: "VC2M9M05", q: "Present value: need $10,000 in 5 years at 4% p.a. CI. How much to invest now?", a: "PV = 10000 / 1.04 to the 5 = $8219.27" },
      { tier: 3, type: "worded", vc: "VC2M9M05", q: "Car: $25,000, depreciates 15%/yr. When is it worth less than $10,000?", a: "0.85 to the n < 0.4; n > log(0.4)/log(0.85) = approx 5.4; after 6 years" },
      { tier: 3, type: "worded", vc: "VC2M9M05", q: "Inflation: $100 today at 3% p.a. inflation. Equivalent value in 20 years?", a: "100 x 1.03 to the 20 = $180.61" },
      { tier: 3, type: "show", vc: "VC2M9M05", q: "Mobile plan: $60/month for 24 months vs $1200 upfront. Total cost of each? Which is better?", a: "$60 x 24 = $1440 vs $1200 upfront. Upfront saves $240." },
      { tier: 3, type: "worded", vc: "VC2M9M05", q: "Investment doubles in 9 years CI. Find the annual interest rate.", a: "(1+r) to the 9 = 2; r = 2 to the 1/9 - 1 = approx 8.01%" },
      { tier: 3, type: "worded", vc: "VC2M9M05", q: "CI monthly: P=$3000, r=8% p.a. for 2 years. Find total amount.", a: "r per month = 8/12 = 0.667%; n=24; A = 3000 x 1.00667 to the 24 = $3517.62" },
      { tier: 3, type: "mc",  vc: "VC2M9M05", q: "Best investment over 5 years from $10,000:\nA) 6% p.a. CI\nB) 6.1% p.a. SI", a: "A) 6% CI: $13,382; B) 6.1% SI: $13,050. CI is better." },
      { tier: 4, type: "show", vc: "VC2M9M05", q: "$5000 at 6% p.a. SI vs 6% p.a. CI for 10 years. Which earns more and by how much?", a: "SI total: $8000; CI total: 5000 x 1.06 to the 10 = $8954.24; CI earns $954.24 more" },
      { tier: 4, type: "show", vc: "VC2M9M05", q: "At what annual CI rate does $2000 grow to $3000 in 8 years?", a: "(1+r) to the 8 = 1.5; r = 1.5 to the 1/8 - 1 = approx 5.24%" },
      { tier: 4, type: "worded", vc: "VC2M9M05", q: "Effective annual rate for 12% p.a. compounded monthly?", a: "(1.01) to the 12 - 1 = approx 12.68%" },
      { tier: 4, type: "show", vc: "VC2M9M05", q: "Prove CI always gives more than SI for same rate and n > 1 when r > 0.", a: "At n=2: CI = P(1+r) squared = P + 2Pr + Pr squared; SI = P + 2Pr; Difference = Pr squared > 0 when r > 0" },
    ]
  },

  // ── YEAR 9 — STATISTICS ──
  { year: 9, strand: "Statistics", topic: "Data Analysis", skill: "Comparing data sets — mean, median, IQR", vc: "VC2M9ST01",
    prereqs: ["Mean median mode", "Range", "Data displays"],
    btbEasy: "Find mean of: 3, 7, 8, 9, 13",
    btbHard: "Dataset: 5, 8, 8, 12, 15, 19, 52. Identify outlier. Compare mean with and without it.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M9ST01", q: "Mean of 2, 4, 6", a: "4" },
      { tier: 1, type: "std", vc: "VC2M9ST01", q: "Mode of 3, 5, 5, 7", a: "5" },
      { tier: 1, type: "std", vc: "VC2M9ST01", q: "Range of 2, 9, 4, 7", a: "7" },
      { tier: 1, type: "std", vc: "VC2M9ST01", q: "Median of 1, 3, 5, 7, 9", a: "5" },
      { tier: 1, type: "fill", vc: "VC2M9ST01", q: "IQR = Q3 - ___", a: "Q1" },
      { tier: 1, type: "mc",  vc: "VC2M9ST01", q: "Which average is most affected by outliers?\nA) Median\nB) Mode\nC) Mean\nD) Range", a: "C) Mean" },
      { tier: 1, type: "std", vc: "VC2M9ST01", q: "Median of 2, 4, 6, 8", a: "5" },
      { tier: 1, type: "tf",  vc: "VC2M9ST01", q: "True or False: The median is always one of the values in the dataset.", a: "False — for even number of values, it is the mean of two middle values" },
      { tier: 2, type: "std", vc: "VC2M9ST01", q: "Mean of 3, 7, 8, 9, 13", a: "8" },
      { tier: 2, type: "std", vc: "VC2M9ST01", q: "Median of 5, 8, 8, 12, 15, 19, 52", a: "12" },
      { tier: 2, type: "std", vc: "VC2M9ST01", q: "IQR: Q1 = 6, Q3 = 18", a: "12" },
      { tier: 2, type: "std", vc: "VC2M9ST01", q: "Outlier fence: Q3 + 1.5 x IQR. Q3=20, IQR=8. Upper fence?", a: "32" },
      { tier: 2, type: "worded", vc: "VC2M9ST01", q: "5 values total to 65. Mean?", a: "13" },
      { tier: 2, type: "worded", vc: "VC2M9ST01", q: "Missing value: mean = 10, n = 5, others: 8, 12, 7, 14. Find missing value.", a: "9" },
      { tier: 2, type: "mc",  vc: "VC2M9ST01", q: "A dataset has mean 8 and median 5. The data is likely:\nA) Symmetric\nB) Skewed right\nC) Skewed left\nD) Bimodal", a: "B) Skewed right — mean pulled up by high values" },
      { tier: 2, type: "std", vc: "VC2M9ST01", q: "5-number summary for: 3, 5, 7, 9, 11, 13, 15", a: "min=3, Q1=5, median=9, Q3=13, max=15" },
      { tier: 3, type: "show", vc: "VC2M9ST01", q: "Dataset: 5, 8, 8, 12, 15, 19, 52. Is 52 an outlier? Show working.", a: "Q1=8, Q3=19, IQR=11; fence = 19+16.5=35.5; 52>35.5 so yes, outlier" },
      { tier: 3, type: "std", vc: "VC2M9ST01", q: "Mean of 5, 8, 8, 12, 15, 19, 52 (with outlier)", a: "Mean = 127/7 = approx 18.14" },
      { tier: 3, type: "std", vc: "VC2M9ST01", q: "Mean of 5, 8, 8, 12, 15, 19 (without outlier)", a: "Mean = 67/6 = approx 11.17" },
      { tier: 3, type: "worded", vc: "VC2M9ST01", q: "Class of 25 students, mean = 68. Total marks?", a: "1700" },
      { tier: 3, type: "worded", vc: "VC2M9ST01", q: "Groups n=10 mean=70, n=15 mean=80. Combined mean?", a: "(700+1200)/25 = 76" },
      { tier: 3, type: "worded", vc: "VC2M9ST01", q: "New member joins: n=9, mean=14, add value 23. New mean?", a: "(126+23)/10 = 14.9" },
      { tier: 3, type: "error", vc: "VC2M9ST01", q: "Rosa says: the mean is always the best measure of centre. Find an example where this is wrong.", a: "Any skewed dataset or one with outliers — e.g. house prices where a few mansions skew the mean far above typical prices" },
      { tier: 3, type: "worded", vc: "VC2M9ST01", q: "Weighted mean: 40% from test (score 65%), 60% from exam (72%). Final mark?", a: "0.4 x 65 + 0.6 x 72 = 26 + 43.2 = 69.2%" },
      { tier: 4, type: "show", vc: "VC2M9ST01", q: "Dataset 5,8,8,12,15,19,52. Compare mean vs median. Which better represents the data and why?", a: "Mean=18.14, Median=12. Median better — not affected by outlier 52." },
      { tier: 4, type: "show", vc: "VC2M9ST01", q: "Prove that adding constant k to all values shifts mean by k but does not change IQR.", a: "New mean = sum(xi+k)/n = old mean + k. New Q1 = Q1+k, Q3 = Q3+k; IQR unchanged." },
      { tier: 4, type: "worded", vc: "VC2M9ST01", q: "Two datasets same IQR but different medians. What does this tell us?", a: "Same spread around their centres, but different typical values — one group scored higher on average" },
      { tier: 4, type: "worded", vc: "VC2M9ST01", q: "Score needed: 4 tests average 72%, need 80% average over 5 tests. Is the required score possible?", a: "5x80 - 4x72 = 400 - 288 = 112%. Impossible — scores max 100%." },
    ]
  },

  // ── YEAR 9 — PROBABILITY ──
  { year: 9, strand: "Statistics", topic: "Probability", skill: "Theoretical and experimental probability", vc: "VC2M9ST02",
    prereqs: ["Fractions", "Sample spaces", "Complementary events"],
    btbEasy: "Bag has 3 red and 7 blue balls. P(red) = ?",
    btbHard: "Two dice rolled 100 times. Expected number of times sum = 7?",
    questions: [
      { tier: 1, type: "std", vc: "VC2M9ST02", q: "P(flipping a head) =", a: "1/2" },
      { tier: 1, type: "std", vc: "VC2M9ST02", q: "P(rolling a 3 on a fair die) =", a: "1/6" },
      { tier: 1, type: "fill", vc: "VC2M9ST02", q: "P(impossible event) = ___", a: "0" },
      { tier: 1, type: "fill", vc: "VC2M9ST02", q: "P(certain event) = ___", a: "1" },
      { tier: 1, type: "std", vc: "VC2M9ST02", q: "P(A) = 0.3. P(not A) =", a: "0.7" },
      { tier: 1, type: "std", vc: "VC2M9ST02", q: "P(ace from standard deck) =", a: "4/52 = 1/13" },
      { tier: 1, type: "tf",  vc: "VC2M9ST02", q: "True or False: P(rolling an even number) = 1/2", a: "True: 2, 4, 6 — three out of six outcomes" },
      { tier: 1, type: "mc",  vc: "VC2M9ST02", q: "Bag: 3 red, 7 blue. P(blue) =\nA) 3/10\nB) 7/10\nC) 7/3\nD) 3/7", a: "B) 7/10" },
      { tier: 2, type: "std", vc: "VC2M9ST02", q: "Two coins flipped. P(both heads) =", a: "1/4" },
      { tier: 2, type: "std", vc: "VC2M9ST02", q: "Die rolled. P(result > 4) =", a: "2/6 = 1/3" },
      { tier: 2, type: "std", vc: "VC2M9ST02", q: "P(A or B): P(A)=0.4, P(B)=0.3, mutually exclusive.", a: "0.7" },
      { tier: 2, type: "std", vc: "VC2M9ST02", q: "P(A and B): P(A)=0.5, P(B)=0.4, independent.", a: "0.20" },
      { tier: 2, type: "std", vc: "VC2M9ST02", q: "P(sum = 7) on two dice", a: "6/36 = 1/6" },
      { tier: 2, type: "std", vc: "VC2M9ST02", q: "P(at least one head in 2 coin flips)", a: "3/4" },
      { tier: 2, type: "mc",  vc: "VC2M9ST02", q: "Cards without replacement: P(two aces) =\nA) 4/52 x 4/51\nB) 4/52 x 3/51\nC) 4/52 x 4/52\nD) 1/13 x 1/13", a: "B) 4/52 x 3/51 = 1/221" },
      { tier: 2, type: "tf",  vc: "VC2M9ST02", q: "True or False: If P(A) = 0.4, P(B) = 0.3, and P(A and B) = 0.12, then A and B are independent.", a: "True: 0.4 x 0.3 = 0.12 = P(A and B)" },
      { tier: 3, type: "worded", vc: "VC2M9ST02", q: "100 rolls of two dice. Expected number of times sum = 7?", a: "100 x 1/6 = approx 16.7" },
      { tier: 3, type: "std", vc: "VC2M9ST02", q: "P(A union B): P(A)=0.4, P(B)=0.5, P(A and B)=0.2. P(A or B) =", a: "0.7" },
      { tier: 3, type: "std", vc: "VC2M9ST02", q: "P(A given B): P(A and B)=0.2, P(B)=0.5. P(A|B) =", a: "0.4" },
      { tier: 3, type: "worded", vc: "VC2M9ST02", q: "P(at least one six in 3 rolls) =", a: "1 - (5/6) cubed = approx 0.421" },
      { tier: 3, type: "worded", vc: "VC2M9ST02", q: "A die rolled 60 times. The number 4 appeared 12 times. Experimental P(4) =", a: "12/60 = 1/5" },
      { tier: 3, type: "show", vc: "VC2M9ST02", q: "Red bag: 3R, 2B. Blue bag: 1R, 4B. Choose bag randomly then draw. P(red ball) =", a: "1/2 x 3/5 + 1/2 x 1/5 = 3/10 + 1/10 = 4/10 = 2/5" },
      { tier: 3, type: "worded", vc: "VC2M9ST02", q: "P(A) + P(B) = 1.1. Can A and B be mutually exclusive? Why?", a: "No — mutually exclusive means P(A or B) = P(A) + P(B), which would exceed 1. Impossible." },
      { tier: 3, type: "mc",  vc: "VC2M9ST02", q: "A game: win $3 (P=0.2), draw $0 (P=0.5), lose $2 (P=0.3). Expected gain =\nA) $0.60\nB) $0\nC) -$0.60\nD) $1", a: "B) $0 (3x0.2 + 0x0.5 + (-2)x0.3 = 0.6 - 0.6 = 0)" },
      { tier: 4, type: "show", vc: "VC2M9ST02", q: "Bag: 4R, 6B. Draw 2 without replacement. P(different colours) = ?", a: "P(RB) + P(BR) = (4/10)(6/9) + (6/10)(4/9) = 48/90 = 8/15" },
      { tier: 4, type: "show", vc: "VC2M9ST02", q: "P(at least 2 heads in 4 coin flips) = ?", a: "P(2) + P(3) + P(4) = 6/16 + 4/16 + 1/16 = 11/16" },
      { tier: 4, type: "worded", vc: "VC2M9ST02", q: "Medical test: disease 1% prevalence, test 99% accurate. P(disease | positive test) approx?", a: "Bayes: (0.01 x 0.99)/(0.01 x 0.99 + 0.99 x 0.01) = approx 50%. Surprisingly low!" },
      { tier: 4, type: "show", vc: "VC2M9ST02", q: "Prove: for mutually exclusive events A and B, P(A given B) = 0.", a: "P(A and B) = 0 (mutually exclusive); P(A|B) = P(A and B)/P(B) = 0/P(B) = 0" },
    ]
  },

  // ── YEAR 10 — QUADRATICS ──
  { year: 10, strand: "Algebra", topic: "Quadratic Equations", skill: "Solving quadratic equations", vc: "VC2M10A01",
    prereqs: ["Factorising trinomials", "Expanding binomials", "Null factor law"],
    btbEasy: "Solve: x squared + 5x + 6 = 0",
    btbHard: "Solve: 2x squared - 3x - 14 = 0. State sum and product of roots.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M10A01", q: "Factorise: x squared + 5x + 6", a: "(x + 2)(x + 3)" },
      { tier: 1, type: "std", vc: "VC2M10A01", q: "Factorise: x squared + 7x + 12", a: "(x + 3)(x + 4)" },
      { tier: 1, type: "std", vc: "VC2M10A01", q: "Factorise: x squared - 5x + 6", a: "(x - 2)(x - 3)" },
      { tier: 1, type: "std", vc: "VC2M10A01", q: "Solve: (x + 2)(x + 3) = 0", a: "x = -2 or x = -3" },
      { tier: 1, type: "std", vc: "VC2M10A01", q: "Factorise: x squared - 9", a: "(x + 3)(x - 3)" },
      { tier: 1, type: "fill", vc: "VC2M10A01", q: "The null factor law: if (x + a)(x + b) = 0, then x = ___ or x = ___", a: "-a or -b" },
      { tier: 1, type: "mc",  vc: "VC2M10A01", q: "x squared - 16 = 0 has solutions:\nA) x = 4 only\nB) x = -4 only\nC) x = 4 or x = -4\nD) No solution", a: "C) x = 4 or x = -4" },
      { tier: 1, type: "std", vc: "VC2M10A01", q: "Solve: (x - 5)(x + 1) = 0", a: "x = 5 or x = -1" },
      { tier: 2, type: "show", vc: "VC2M10A01", q: "Solve by factorising: x squared + 5x + 6 = 0", a: "(x+2)(x+3) = 0; x = -2 or x = -3" },
      { tier: 2, type: "std", vc: "VC2M10A01", q: "Solve: x squared - 7x + 10 = 0", a: "x = 2 or x = 5" },
      { tier: 2, type: "std", vc: "VC2M10A01", q: "Solve: x squared + 2x - 8 = 0", a: "x = 2 or x = -4" },
      { tier: 2, type: "std", vc: "VC2M10A01", q: "Solve: 2x squared + 5x + 3 = 0", a: "x = -1 or x = -3/2" },
      { tier: 2, type: "std", vc: "VC2M10A01", q: "Solve: x squared + 6x + 9 = 0", a: "x = -3 (double root)" },
      { tier: 2, type: "mc",  vc: "VC2M10A01", q: "Discriminant of x squared + 2x + 5. Number of real solutions?\nA) 0\nB) 1\nC) 2\nD) Infinite", a: "A) 0 — delta = 4 - 20 = -16 < 0" },
      { tier: 2, type: "std", vc: "VC2M10A01", q: "Solve: 3x squared - 7x + 2 = 0", a: "x = 2 or x = 1/3" },
      { tier: 2, type: "tf",  vc: "VC2M10A01", q: "True or False: x squared - 10x + 25 = 0 has two different solutions.", a: "False — it is a perfect square (x-5) squared = 0, one repeated solution x = 5" },
      { tier: 3, type: "show", vc: "VC2M10A01", q: "Complete the square: solve x squared + 4x + 1 = 0", a: "(x+2) squared - 3 = 0; x = -2 +/- root 3" },
      { tier: 3, type: "show", vc: "VC2M10A01", q: "Quadratic formula: solve x squared + 3x - 5 = 0", a: "x = (-3 +/- root(9+20))/2 = (-3 +/- root29)/2" },
      { tier: 3, type: "worded", vc: "VC2M10A01", q: "Rectangle: length is 3 more than width, area = 54. Find dimensions.", a: "w(w+3)=54; w squared +3w-54=0; (w+9)(w-6)=0; w=6, l=9" },
      { tier: 3, type: "worded", vc: "VC2M10A01", q: "Ball: h = -5t squared + 20t. When does it hit the ground?", a: "-5t(t-4) = 0; t = 0 (launch) or t = 4s" },
      { tier: 3, type: "std", vc: "VC2M10A01", q: "Form equation with roots x = 3 and x = -5", a: "(x-3)(x+5) = 0; x squared + 2x - 15 = 0" },
      { tier: 3, type: "show", vc: "VC2M10A01", q: "Prove x squared + x + 1 = 0 has no real roots.", a: "delta = 1 - 4 = -3 < 0; no real roots" },
      { tier: 3, type: "worded", vc: "VC2M10A01", q: "Revenue: R(x) = -2x squared + 80x - 200. Maximum revenue and units?", a: "x = -80/(2 x -2) = 20; R = -800 + 1600 - 200 = $600" },
      { tier: 3, type: "std", vc: "VC2M10A01", q: "Solve: x to the 4 - 5x squared + 4 = 0", a: "Let u = x squared: (u-1)(u-4) = 0; x = +/-1 or +/-2" },
      { tier: 4, type: "show", vc: "VC2M10A01", q: "Solve 2x squared - 3x - 14 = 0. State sum and product of roots.", a: "x = 7/2 or x = -2; sum = 3/2 = -b/a; product = -7 = c/a" },
      { tier: 4, type: "worded", vc: "VC2M10A01", q: "2x squared + bx + 8 = 0 has equal roots. Find b.", a: "delta = b squared - 64 = 0; b = +/-8" },
      { tier: 4, type: "show", vc: "VC2M10A01", q: "Solve and verify: (x - 1) squared = 2(x + 3)", a: "x squared - 4x - 5 = 0; (x-5)(x+1) = 0; x=5 or x=-1. Verify both." },
      { tier: 4, type: "show", vc: "VC2M10A01", q: "For what values of k does x squared - (k+2)x + 2k = 0 have equal roots?", a: "delta = (k+2) squared - 8k = 0; k squared - 4k + 4 = 0; (k-2) squared = 0; k = 2" },
    ]
  },

  // ── YEAR 11 — FUNCTIONS ──
  { year: 11, strand: "Algebra", topic: "Functions", skill: "Domain, range and function notation", vc: "VC2M11A01",
    prereqs: ["Coordinates", "Graphing linear and quadratic functions", "Equation solving"],
    btbEasy: "State the domain of f(x) = 1/(x - 3)",
    btbHard: "f(x) = sqrt(4 - x squared): state domain, range and describe the graph.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M11A01", q: "Domain of f(x) = x + 2", a: "All real x" },
      { tier: 1, type: "std", vc: "VC2M11A01", q: "Domain of f(x) = sqrt(x)", a: "x >= 0" },
      { tier: 1, type: "std", vc: "VC2M11A01", q: "Domain of f(x) = 1/x", a: "x not equal to 0" },
      { tier: 1, type: "std", vc: "VC2M11A01", q: "Range of f(x) = x squared", a: "y >= 0" },
      { tier: 1, type: "fill", vc: "VC2M11A01", q: "A function assigns ___ output to each input.", a: "exactly one" },
      { tier: 1, type: "mc",  vc: "VC2M11A01", q: "Which graph passes the vertical line test?\nA) x = 4\nB) y = x squared\nC) x squared + y squared = 9\nD) y squared = x", a: "B) y = x squared" },
      { tier: 1, type: "std", vc: "VC2M11A01", q: "f(2) for f(x) = 3x - 1", a: "5" },
      { tier: 1, type: "tf",  vc: "VC2M11A01", q: "True or False: y = x squared is a one-to-one function.", a: "False — both x=2 and x=-2 give y=4" },
      { tier: 2, type: "std", vc: "VC2M11A01", q: "Domain of f(x) = sqrt(x - 4)", a: "x >= 4" },
      { tier: 2, type: "std", vc: "VC2M11A01", q: "Domain of f(x) = 1/(x - 3)", a: "x not equal to 3" },
      { tier: 2, type: "std", vc: "VC2M11A01", q: "Domain of f(x) = ln(x + 2)", a: "x > -2" },
      { tier: 2, type: "std", vc: "VC2M11A01", q: "Range of f(x) = -x squared + 4", a: "y <= 4" },
      { tier: 2, type: "std", vc: "VC2M11A01", q: "g(x) = x squared - 1. Solve g(x) = 8.", a: "x = +/-3" },
      { tier: 2, type: "show", vc: "VC2M11A01", q: "f(x) = 2x + 1. Find f(3) + f(-3).", a: "f(3)=7; f(-3)=-5; sum = 2" },
      { tier: 2, type: "mc",  vc: "VC2M11A01", q: "Even functions satisfy:\nA) f(-x) = f(x)\nB) f(-x) = -f(x)\nC) f(x) = 0 for all x\nD) f(x) > 0", a: "A) f(-x) = f(x)" },
      { tier: 2, type: "std", vc: "VC2M11A01", q: "Is f(x) = x squared - 2 even, odd, or neither?", a: "Even: f(-x) = (-x) squared - 2 = x squared - 2 = f(x)" },
      { tier: 3, type: "show", vc: "VC2M11A01", q: "f(x) = sqrt(9 - x squared). Find domain and range.", a: "Domain: -3 <= x <= 3; Range: 0 <= y <= 3" },
      { tier: 3, type: "show", vc: "VC2M11A01", q: "f(x) = 2x, g(x) = x + 1. Find f(g(x)) and g(f(x)).", a: "f(g(x)) = 2(x+1) = 2x+2; g(f(x)) = 2x+1; not equal" },
      { tier: 3, type: "show", vc: "VC2M11A01", q: "Find inverse of f(x) = 2x + 3.", a: "Swap x and y: x = 2y+3; y = (x-3)/2; f inverse(x) = (x-3)/2" },
      { tier: 3, type: "show", vc: "VC2M11A01", q: "g(f(3)) where f(x) = x squared and g(x) = x + 1.", a: "f(3) = 9; g(9) = 10" },
      { tier: 3, type: "std", vc: "VC2M11A01", q: "Range of f(x) = 3 - 2x squared", a: "y <= 3" },
      { tier: 3, type: "show", vc: "VC2M11A01", q: "Find inverse of f(x) = x squared + 1 (restrict domain to x >= 0).", a: "y = x squared + 1; x = sqrt(y-1); f inverse(x) = sqrt(x-1), x >= 1" },
      { tier: 3, type: "mc",  vc: "VC2M11A01", q: "The horizontal line test determines:\nA) If a relation is a function\nB) If a function is one-to-one\nC) The domain\nD) The range", a: "B) If a function is one-to-one (has an inverse function)" },
      { tier: 3, type: "show", vc: "VC2M11A01", q: "Piecewise: f(x) = x squared for x < 0, and 2x for x >= 0. Find f(-2) + f(3).", a: "f(-2) = 4; f(3) = 6; sum = 10" },
      { tier: 4, type: "show", vc: "VC2M11A01", q: "f(x) = sqrt(4 - x squared): domain, range, describe graph.", a: "Domain: -2 <= x <= 2; Range: 0 <= y <= 2; upper semicircle radius 2" },
      { tier: 4, type: "show", vc: "VC2M11A01", q: "f(x) = (x squared - 1)/(x - 1). Simplify and state domain.", a: "f(x) = x + 1 for x not equal to 1; domain: all reals except x = 1" },
      { tier: 4, type: "show", vc: "VC2M11A01", q: "Prove f composed with f inverse (x) = x for f(x) = 3x - 5.", a: "f inverse = (x+5)/3; f(f inverse(x)) = 3 x (x+5)/3 - 5 = x+5-5 = x" },
      { tier: 4, type: "show", vc: "VC2M11A01", q: "For what values of k does f(x) = x squared + kx + 4 have no real zeros?", a: "delta < 0: k squared - 16 < 0; -4 < k < 4" },
    ]
  },

  // ── YEAR 12 — DIFFERENTIATION ──
  { year: 12, strand: "Algebra", topic: "Calculus — Differentiation", skill: "Differentiating polynomial functions", vc: "VC2M12A01",
    prereqs: ["Gradient of a line", "Index notation", "Algebraic manipulation"],
    btbEasy: "Differentiate: f(x) = 3x squared + 5x - 2",
    btbHard: "Particle: s(t) = 2t cubed - 9t squared + 12t. Find when velocity = 0 and classify these points.",
    questions: [
      { tier: 1, type: "std", vc: "VC2M12A01", q: "d/dx (x cubed) =", a: "3x squared" },
      { tier: 1, type: "std", vc: "VC2M12A01", q: "d/dx (x to the 4) =", a: "4x cubed" },
      { tier: 1, type: "std", vc: "VC2M12A01", q: "d/dx (5x) =", a: "5" },
      { tier: 1, type: "std", vc: "VC2M12A01", q: "d/dx (7) =", a: "0" },
      { tier: 1, type: "fill", vc: "VC2M12A01", q: "Power rule: d/dx (x to the n) = ___", a: "n x to the (n-1)" },
      { tier: 1, type: "std", vc: "VC2M12A01", q: "d/dx (3x squared) =", a: "6x" },
      { tier: 1, type: "mc",  vc: "VC2M12A01", q: "d/dx (x squared + x) =\nA) 2x\nB) x + 1\nC) 2x + 1\nD) 2x squared + x", a: "C) 2x + 1" },
      { tier: 1, type: "std", vc: "VC2M12A01", q: "d/dx (2x cubed) =", a: "6x squared" },
      { tier: 2, type: "std", vc: "VC2M12A01", q: "f(x) = 4x cubed - 3x + 2. Find f prime(x).", a: "12x squared - 3" },
      { tier: 2, type: "std", vc: "VC2M12A01", q: "f(x) = 5x to the 4 + 2x squared - 7. Find f prime(x).", a: "20x cubed + 4x" },
      { tier: 2, type: "std", vc: "VC2M12A01", q: "Find f prime(2) for f(x) = 3x squared - 4x.", a: "f prime(x) = 6x - 4; f prime(2) = 8" },
      { tier: 2, type: "std", vc: "VC2M12A01", q: "Gradient at x = 3: y = x squared - 5x", a: "f prime(3) = 6 - 5 = 1" },
      { tier: 2, type: "std", vc: "VC2M12A01", q: "When is gradient zero? f(x) = x squared - 6x + 8", a: "f prime(x) = 2x - 6 = 0; x = 3" },
      { tier: 2, type: "show", vc: "VC2M12A01", q: "Find f prime(-1) for f(x) = x cubed + 2x.", a: "f prime(x) = 3x squared + 2; f prime(-1) = 3 + 2 = 5" },
      { tier: 2, type: "mc",  vc: "VC2M12A01", q: "At a stationary point, the gradient equals:\nA) 1\nB) -1\nC) 0\nD) Undefined", a: "C) 0" },
      { tier: 2, type: "std", vc: "VC2M12A01", q: "f(x) = 2x cubed - x squared + 4x - 1. Find f prime(x).", a: "6x squared - 2x + 4" },
      { tier: 3, type: "show", vc: "VC2M12A01", q: "Find stationary points of f(x) = x cubed - 6x squared + 9x.", a: "f prime = 3x squared - 12x + 9 = 0; 3(x-1)(x-3) = 0; x = 1 and x = 3" },
      { tier: 3, type: "show", vc: "VC2M12A01", q: "Classify stationary points of f(x) = x cubed - 3x.", a: "f prime = 3x squared - 3 = 0; x = +/-1; f double-prime = 6x; x=-1: max; x=1: min" },
      { tier: 3, type: "show", vc: "VC2M12A01", q: "Equation of tangent at x = 2: y = x squared + 3x.", a: "gradient = 4+3=7; point (2,10); y - 10 = 7(x-2); y = 7x - 4" },
      { tier: 3, type: "show", vc: "VC2M12A01", q: "Normal to y = x squared at x = 3.", a: "gradient of curve = 6; normal gradient = -1/6; point (3,9); y - 9 = -1/6(x-3); y = -x/6 + 11/2" },
      { tier: 3, type: "worded", vc: "VC2M12A01", q: "State intervals where f(x) = x squared - 4x + 3 is increasing and decreasing.", a: "f prime = 2x - 4; decreasing for x < 2; increasing for x > 2" },
      { tier: 3, type: "std", vc: "VC2M12A01", q: "d squared y / dx squared for y = 3x to the 4 - 2x cubed", a: "36x squared - 12x" },
      { tier: 3, type: "mc",  vc: "VC2M12A01", q: "Chain rule: d/dx (3x squared + 1) to the 4 =\nA) 4(3x squared + 1) cubed\nB) 24x(3x squared + 1) cubed\nC) 4x(3x squared + 1) cubed\nD) 12(3x squared + 1) cubed", a: "B) 24x(3x squared + 1) cubed" },
      { tier: 3, type: "show", vc: "VC2M12A01", q: "Tangent to y = x cubed at (2, 8). Find equation.", a: "gradient = 3(4) = 12; y - 8 = 12(x-2); y = 12x - 16" },
      { tier: 4, type: "show", vc: "VC2M12A01", q: "s(t) = 2t cubed - 9t squared + 12t. Find when velocity = 0 and classify.", a: "v(t) = 6t squared - 18t + 12 = 0; t = 1 and t = 2; a(1) = -6 < 0 (max speed); a(2) = 6 > 0 (min speed)" },
      { tier: 4, type: "show", vc: "VC2M12A01", q: "Max area: 40m fence, one side is a wall. Find optimal dimensions.", a: "A = x(40-2x); A prime = 40 - 4x = 0; x = 10; dimensions 10m x 20m; area = 200 sq m" },
      { tier: 4, type: "show", vc: "VC2M12A01", q: "Product rule: differentiate y = x squared times sin(x).", a: "y prime = 2x sin(x) + x squared cos(x)" },
      { tier: 4, type: "show", vc: "VC2M12A01", q: "Profit P(x) = -2x squared + 80x - 200. Find maximum profit and units produced.", a: "P prime = -4x + 80 = 0; x = 20; P(20) = -800 + 1600 - 200 = $600" },
    ]
  },
]

// Foundational always-reviewed skills
export const FOUNDATIONAL = [
  { label: "Times Tables", strand: "Number",
    btbEasy: "Calculate: 336 divided by 14",
    btbHard: "If 37 x 43 = 1591, find 370 x 4.3",
    questions: [
      { tier: 1, type: "std", q: "7 x 8 =", a: "56" }, { tier: 1, type: "std", q: "9 x 6 =", a: "54" },
      { tier: 1, type: "std", q: "12 x 7 =", a: "84" }, { tier: 1, type: "std", q: "8 x 8 =", a: "64" },
      { tier: 2, type: "std", q: "13 x 7 =", a: "91" }, { tier: 2, type: "std", q: "15 x 6 =", a: "90" },
      { tier: 2, type: "std", q: "14 x 9 =", a: "126" }, { tier: 2, type: "std", q: "17 x 8 =", a: "136" },
      { tier: 3, type: "std", q: "24 x 5 =", a: "120" }, { tier: 3, type: "std", q: "32 x 4 =", a: "128" },
      { tier: 3, type: "std", q: "18 x 7 =", a: "126" }, { tier: 3, type: "std", q: "25 x 9 =", a: "225" },
      { tier: 4, type: "std", q: "23 x 17 =", a: "391" }, { tier: 4, type: "std", q: "34 x 16 =", a: "544" },
      { tier: 4, type: "std", q: "47 x 12 =", a: "564" }, { tier: 4, type: "std", q: "56 x 25 =", a: "1400" },
    ]
  },
  { label: "BIDMAS — Order of Operations", strand: "Number",
    btbEasy: "8 + 2 x (9 - 4) squared - 3 =",
    btbHard: "(3 squared - root(25)) cubed divided by (2 + 6 x 0) + 4! =",
    questions: [
      { tier: 1, type: "std", q: "3 + 4 x 2 =", a: "11" }, { tier: 1, type: "std", q: "(3 + 4) x 2 =", a: "14" },
      { tier: 1, type: "std", q: "10 - 2 squared =", a: "6" }, { tier: 1, type: "std", q: "5 x 3 + 8 / 2 =", a: "19" },
      { tier: 2, type: "std", q: "3 + (6 - 2) squared =", a: "19" }, { tier: 2, type: "std", q: "4 x 3 squared - 10 =", a: "26" },
      { tier: 2, type: "std", q: "(2 + 3) squared - 4 x 3 =", a: "13" }, { tier: 2, type: "std", q: "18 / (2 + 4) x 3 =", a: "9" },
      { tier: 3, type: "std", q: "2 cubed + 4 x (7 - 3) =", a: "24" }, { tier: 3, type: "std", q: "(5 - 2) cubed / 9 + 4 =", a: "7" },
      { tier: 3, type: "std", q: "root(16 + 9) x 2 =", a: "10" }, { tier: 3, type: "std", q: "3 x 2 squared - (8 - 3) squared / 5 =", a: "7" },
      { tier: 4, type: "std", q: "(2 cubed + 4 squared) / (root(36) - 1) =", a: "24/5 = 4.8" },
      { tier: 4, type: "error", q: "Sam writes: 8 + 2 x 5 = 50. Find the error.", a: "Must multiply first: 8 + 10 = 18" },
      { tier: 4, type: "std", q: "4! / (3 + 1) + 2 squared =", a: "6 + 4 = 10" },
      { tier: 4, type: "std", q: "(-2) cubed + 3 x (-1) squared - 5 =", a: "-8 + 3 - 5 = -10" },
    ]
  },
  { label: "Fractions — Operations", strand: "Number",
    btbEasy: "3/4 divided by 1/2 + 2/3 x 3/4 =",
    btbHard: "Simplify: (2/3 x 9/4) divided by (1/2 + 2/3)",
    questions: [
      { tier: 1, type: "std", q: "1/2 + 1/4 =", a: "3/4" }, { tier: 1, type: "std", q: "3/4 - 1/4 =", a: "1/2" },
      { tier: 1, type: "std", q: "2/3 + 1/6 =", a: "5/6" }, { tier: 1, type: "std", q: "1/2 x 4 =", a: "2" },
      { tier: 2, type: "std", q: "3/4 + 2/3 =", a: "17/12 = 1 and 5/12" }, { tier: 2, type: "std", q: "5/6 - 3/4 =", a: "1/12" },
      { tier: 2, type: "std", q: "2/3 x 3/4 =", a: "1/2" }, { tier: 2, type: "std", q: "3/4 / (3/8) =", a: "2" },
      { tier: 3, type: "std", q: "1 and 3/4 + 2 and 1/3 =", a: "4 and 1/12" }, { tier: 3, type: "std", q: "2 and 1/2 - 1 and 3/4 =", a: "3/4" },
      { tier: 3, type: "std", q: "1 and 1/2 x 2 and 2/3 =", a: "4" }, { tier: 3, type: "std", q: "2 and 1/4 / (3/4) =", a: "3" },
      { tier: 4, type: "show", q: "(3/4 + 1/3) x (2/3 - 1/4) =", a: "(9+4)/12 x (8-3)/12 = 13/12 x 5/12 = 65/144" },
      { tier: 4, type: "worded", q: "If 3/5 of a number is 18, find the number.", a: "30" },
      { tier: 4, type: "show", q: "Which is larger: 7/12 or 5/8? Show working.", a: "14/24 vs 15/24 — 5/8 is larger" },
      { tier: 4, type: "error", q: "Tom adds: 2/3 + 1/4 = 3/7. Find his error.", a: "Cannot add numerators and denominators. Correct: 8/12 + 3/12 = 11/12" },
    ]
  },
  { label: "Decimals and Place Value", strand: "Number",
    btbEasy: "4.5 x 3.6 = ?",
    btbHard: "(1.5) cubed - (0.5) cubed = ?",
    questions: [
      { tier: 1, type: "std", q: "3.6 + 2.4 =", a: "6.0" }, { tier: 1, type: "std", q: "5.2 - 1.8 =", a: "3.4" },
      { tier: 1, type: "std", q: "4 x 0.3 =", a: "1.2" }, { tier: 1, type: "std", q: "2.4 / 4 =", a: "0.6" },
      { tier: 2, type: "std", q: "3.14 x 2 =", a: "6.28" }, { tier: 2, type: "std", q: "4.56 / 0.8 =", a: "5.7" },
      { tier: 2, type: "std", q: "0.4 x 0.3 =", a: "0.12" }, { tier: 2, type: "std", q: "12.6 / 0.3 =", a: "42" },
      { tier: 3, type: "std", q: "Round 3.456 to 2 decimal places", a: "3.46" },
      { tier: 3, type: "std", q: "0.125 as a fraction =", a: "1/8" },
      { tier: 3, type: "std", q: "1.2 cubed =", a: "1.728" }, { tier: 3, type: "std", q: "0.007 x 400 =", a: "2.8" },
      { tier: 4, type: "std", q: "4.5 x 10 to the -3 as a decimal =", a: "0.0045" },
      { tier: 4, type: "std", q: "(0.3) squared + (0.4) squared =", a: "0.25" },
      { tier: 4, type: "std", q: "If 2.5x = 17.5, find x.", a: "7" },
      { tier: 4, type: "show", q: "Solve: 1.2y - 0.4 = 2.84. Show steps.", a: "1.2y = 3.24; y = 2.7" },
    ]
  },
  { label: "Percentages", strand: "Number",
    btbEasy: "A coat costs $180 after a 10% discount. Original price?",
    btbHard: "Successive discounts: 20%, 15%, 10% off $500. Final price?",
    questions: [
      { tier: 1, type: "std", q: "10% of 80 =", a: "8" }, { tier: 1, type: "std", q: "50% of 64 =", a: "32" },
      { tier: 1, type: "std", q: "25% of 120 =", a: "30" }, { tier: 1, type: "std", q: "20% of 45 =", a: "9" },
      { tier: 2, type: "std", q: "15% of 60 =", a: "9" }, { tier: 2, type: "std", q: "Increase 80 by 25%", a: "100" },
      { tier: 2, type: "std", q: "Decrease 200 by 15%", a: "170" }, { tier: 2, type: "std", q: "$36 is 40% of what?", a: "$90" },
      { tier: 3, type: "std", q: "% increase: 40 to 55 =", a: "37.5%" }, { tier: 3, type: "std", q: "Score 34/40 as %", a: "85%" },
      { tier: 3, type: "std", q: "After 20% off, item costs $72. Original?", a: "$90" },
      { tier: 3, type: "std", q: "GST (10%) added to $450. Total?", a: "$495" },
      { tier: 4, type: "show", q: "Successive: 20% increase then 15% decrease. Net % change?", a: "1.20 x 0.85 = 1.02; 2% increase" },
      { tier: 4, type: "std", q: "Price rises 8% then falls 8%. Net change?", a: "-0.64% (loss)" },
      { tier: 4, type: "std", q: "$P at 5% CI. After how many years > $2P?", a: "n > log2/log1.05 = approx 14.2; 15 years" },
      { tier: 4, type: "worded", q: "Successive discounts 20%, 15%, 10% off $500. Final price?", a: "$500 x 0.80 x 0.85 x 0.90 = $306" },
    ]
  },
]
